project_id = "qmuxdkxdrxevlnckssuw"

[functions.generate-pages]
verify_jwt = false

[functions.publish-pages]
verify_jwt = false

[functions.scan-template]
verify_jwt = false

[functions.discover-templates]
verify_jwt = false

[functions.admin-panel]
verify_jwt = false

[functions.generate-template]
verify_jwt = false

[functions.build-internal-links]
verify_jwt = false

[functions.generate-store]
verify_jwt = false