project_id = "qmuxdkxdrxevlnckssuw"

[functions.generate-pages]
verify_jwt = false

[functions.publish-pages]
verify_jwt = false

[functions.scan-template]
verify_jwt = false

[functions.discover-templates]
verify_jwt = false