// Edge function: AI-generate CSV-like rows for a template's variables.
import { aiGenerate, extractAuthToken } from "../_shared/ai-service.ts";
import {
  analyzeTemplateBudget,
  analyzeTemplateContentBudget,
  buildBudgetPromptHints,
  enforceRowBudget,
} from "../_shared/template-length-budget.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface Body {
  variables: string[];
  count: number;
  business?: string;
  niche?: string;
  service?: string;
  language?: string;
  country?: string;
  /** Original template sample values used to derive per-field length budgets. */
  defaultValues?: Record<string, string>;
  /** Template HTML fallback used when sample values are unavailable. */
  templateContent?: string;
  /** Template Safe Mode: enforce length budgets so content never breaks layout. */
  templateSafeMode?: boolean;
  /** Rows already generated by the client in earlier batches. Avoid repeating them. */
  previousRows?: Record<string, string>[];
}

const MAX_ROWS_PER_REQUEST = 10;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const body = (await req.json()) as Body;
    const variables = (body.variables || []).filter((v) => typeof v === "string" && v.trim().length > 0);
    const requestedCount = Math.max(1, Number(body.count) || 10);
    const count = Math.min(requestedCount, MAX_ROWS_PER_REQUEST);

    if (variables.length === 0) {
      return new Response(JSON.stringify({ error: "At least one variable is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const ctx = [
      body.business ? `Business: ${body.business}` : null,
      body.niche ? `Niche / Industry: ${body.niche}` : null,
      body.service ? `Service / Product: ${body.service}` : null,
      body.country ? `Country: ${body.country}` : null,
      body.language ? `Language for values: ${body.language}` : null,
    ]
      .filter(Boolean)
      .join("\n");

    const safeMode = body.templateSafeMode !== false; // default ON
    const sampleBudget = analyzeTemplateBudget(body.defaultValues);
    const budget = Object.keys(sampleBudget).length > 0 ? sampleBudget : analyzeTemplateContentBudget(body.templateContent);
    const budgetHints = safeMode ? buildBudgetPromptHints(budget) : "";

    const systemPrompt = `You generate realistic dataset rows for a programmatic SEO page generator.
Each row must contain ONE value for every requested variable. Values must be:
- Specific and realistic${body.country ? ", locally relevant where possible" : " — DO NOT invent city, country, region, or any location-based phrasing unless a variable explicitly asks for it"}
- DISTINCT ACROSS ROWS for EVERY field — no two rows may share the same value for the same field. This includes headings like hero_title / hero_subtitle / about_title / cta_title / services_title: rewrite each in a completely different phrasing, angle, wording, tone and structure per row.
- Never copy the sample/default values verbatim — treat samples only as a length/style reference, then invent fresh wording.
- Concise: match each template field's original word count; never expand descriptions
- In the requested language
- Plain text only (no markdown, no quotes, no escapes)
${budgetHints ? "\nTEMPLATE SAFE MODE — design integrity is more important than content length. Keep every title/description within the exact listed word and character budget. " + budgetHints + "\n" : ""}Return through the provided tool function, never as free text.`;

    const sampleHint = body.defaultValues && Object.keys(body.defaultValues).length > 0
      ? `\n\nReference sample values (DO NOT COPY — only use them to gauge tone and length; rewrite every field with fresh, distinct wording per row):\n${Object.entries(body.defaultValues).slice(0, 40).map(([k, v]) => `- ${k}: ${String(v).slice(0, 160)}`).join("\n")}`
      : "";

    const previousRows = Array.isArray(body.previousRows) ? body.previousRows.slice(-80) : [];
    const previousHint = previousRows.length > 0
      ? `\n\nAlready generated values (DO NOT reuse or near-copy these):\n${variables.map((v) => {
        const values = Array.from(new Set(previousRows.map((r) => String(r?.[v] ?? "").trim()).filter(Boolean))).slice(-30);
        return values.length ? `- ${v}: ${values.join(" | ")}` : "";
      }).filter(Boolean).join("\n")}`
      : "";

    const userPrompt = `Generate ${count} unique rows.
Variables (column names): ${variables.join(", ")}

Context:
${ctx || "(no extra context — be sensible)"}${sampleHint}${previousHint}

Diversity rules (STRICT):
- For every field, all ${count} rows must have DIFFERENT values. No repeats, no near-duplicates.
- Vary sentence openings, verbs, adjectives and structure between rows.
- Do NOT echo the reference sample values — those are just style/length hints.
Make every row meaningfully different so each generated page is unique.`;

    const tool = {
      type: "function",
      function: {
        name: "emit_rows",
        description: "Return the generated dataset rows.",
        parameters: {
          type: "object",
          properties: {
            rows: {
              type: "array",
              minItems: 1,
              items: {
                type: "object",
                properties: Object.fromEntries(variables.map((v) => [v, { type: "string" }])),
                required: variables,
                additionalProperties: false,
              },
            },
          },
          required: ["rows"],
          additionalProperties: false,
        },
      },
    };

    const result = await aiGenerate({
      authToken: extractAuthToken(req),
      promptType: "medium_content",
      model: "google/gemini-2.5-flash",
      temperature: 0.95,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      tools: [tool],
      tool_choice: { type: "function", function: { name: "emit_rows" } },
    });

    if (!result.success) {
      const statusCode = result.content.includes("429") ? 429 : result.content.includes("402") ? 402 : 500;
      return new Response(JSON.stringify({ error: result.content }), {
        status: statusCode,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    let parsed: any;
    try {
      parsed = typeof result.content === "string" ? JSON.parse(result.content) : result.content;
    } catch {
      return new Response(JSON.stringify({ error: "AI returned invalid row data. Please try again." }), {
        status: 502,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const rows: Record<string, string>[] = Array.isArray(parsed.rows) ? parsed.rows : [];
    const final = rows.slice(0, count).map((r) => {
      const out: Record<string, string> = {};
      for (const v of variables) out[v] = String(r?.[v] ?? "").trim();
      return safeMode ? enforceRowBudget(out, budget) : out;
    });

    if (final.length === 0) {
      return new Response(JSON.stringify({ error: "AI returned no rows. Please try again." }), {
        status: 502,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ rows: final }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("ai-generate-rows error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
