// Auto-generated by scripts/generate-locales.ts — DO NOT EDIT BY HAND
// Edit the JSON files in src/i18n/locales-json/ and run: bun scripts/generate-locales.ts

import enLocale from "./locales/en";

export type Language = "en" | "fr" | "de" | "es";

export const languages: { code: Language; label: string; flag: string }[] = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "es", label: "Español", flag: "🇪🇸" },
];

/**
 * English ships in the main bundle; the other locales are fetched on demand so
 * the first page load stays small.
 */
export const translations: Record<string, Record<string, string>> = {
  en: enLocale,
};

const loaders: Record<Language, () => Promise<{ default: Record<string, string> }>> = {
  en: async () => ({ default: enLocale }),
  fr: () => import("./locales/fr"),
  de: () => import("./locales/de"),
  es: () => import("./locales/es"),
};

const pending: Partial<Record<Language, Promise<void>>> = {};

/** Loads a locale bundle once and merges it into `translations`. */
export function loadLocale(lang: Language): Promise<void> {
  if (translations[lang]) return Promise.resolve();
  if (!pending[lang]) {
    pending[lang] = loaders[lang]()
      .then((mod) => {
        translations[lang] = mod.default;
      })
      .catch(() => {
        /* fall back to English */
      });
  }
  return pending[lang]!;
}
