import { Seo } from "@/components/Seo";
import { Link } from "react-router-dom";
import { useEffect, useState, useRef } from "react";
import { usePageAutoTranslate } from "@/i18n/usePageAutoTranslate";
import {
  LayoutDashboard, Globe, Rocket, Layers, FileText, Store, Database,
  KeyRound, Zap, Columns3, BarChart3, Activity, CalendarDays,
  ClipboardCheck, Search, Gift, CreditCard, Settings, Users,
  ArrowRight, BookOpen, CheckCircle2, Lightbulb, AlertCircle,
  Sparkles, SlidersHorizontal, Link2, Plug,
} from "lucide-react";
import { LandingNav } from "@/components/landing/LandingNav";
import { LandingFooter } from "@/components/landing/LandingFooter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

interface GuideStep {
  title: string;
  detail: string;
}

interface ToolDoc {
  id: string;
  icon: React.ElementType;
  name: string;
  group: string;
  short: string;
  steps: string[];
  tips?: string[];
  /** Optional in-depth, numbered walkthrough shown below the quick steps. */
  guide?: GuideStep[];
}


const TOOLS: ToolDoc[] = [
  {
    id: "dashboard", icon: LayoutDashboard, group: "Core", name: "Dashboard",
    short: "All workspace activity, recent campaigns and quick stats in one place.",
    steps: [
      "After login you land on the Dashboard by default.",
      "Top cards show total campaigns, generated pages and connected websites.",
      "Click any recent campaign card to jump straight into its detail view.",
      "Quick action buttons let you create a new campaign or template.",
    ],
    tips: ["On day one, start with 'Connect Website' from here."],
  },
  {
    id: "websites", icon: Globe, group: "Core", name: "Websites",
    short: "Connect WordPress, WooCommerce, Shopify and PrestaShop sites.",
    steps: [
      "Click the '+ Add Website' button.",
      "Pick your platform (WordPress / Shopify / WooCommerce / PrestaShop).",
      "Enter the site URL and credentials (App Password / API key).",
      "Hit 'Test Connection' — a green tick means you can save.",
      "Content from the connected site will be pulled in automatically.",
    ],
    tips: [
      "For WordPress, always use an Application Password — never the regular password.",
      "If you see an SSL error, check whether the URL needs www or not.",
    ],
  },
  {
    id: "ai-site-builder", icon: Sparkles, group: "Core", name: "AI Site Builder",
    short: "Describe your business and get a full multi-page site design generated by AI.",
    steps: [
      "Open 'AI Site Builder' from the sidebar.",
      "Enter your business name, niche and the services you offer.",
      "Pick a brand style / vibe — colors and fonts are applied automatically.",
      "AI builds the pages, sections, copy and images in one pass.",
      "Send the result straight to Templates or publish to a connected website.",
    ],
    tips: [
      "Images use Unsplash first and only fall back to AI generation when needed — this keeps credits low.",
      "You can regenerate any single section without rebuilding the whole site.",
    ],
    guide: [
      { title: "Open the builder", detail: "Sidebar → AI Site Builder. You start on a single input form — no design skills needed." },
      { title: "Describe your business", detail: "Type your business name, the niche/industry, and a short list of the services or products you offer. The more specific you are, the better the copy." },
      { title: "Choose a language & location (optional)", detail: "Set the primary language and target country so the generated copy and tone match your audience." },
      { title: "Pick a brand vibe", detail: "Select a style/vibe preset. This locks the color palette, fonts and section rhythm before generation so the whole site feels consistent." },
      { title: "Generate", detail: "Click Generate. AI builds every page — hero, features, services, testimonials, FAQ, contact — with matching copy and images in one pass." },
      { title: "Review & refine", detail: "Scroll the live preview. Use the per-section regenerate to redo just one block instead of the whole site." },
      { title: "Save or publish", detail: "Send the result to Templates to reuse it in campaigns, or publish directly to a connected website." },
    ],
  },
  {
    id: "campaigns", icon: Rocket, group: "Core", name: "Campaigns",
    short: "Create and manage campaigns for bulk page generation.",
    steps: [
      "Click 'Create Campaign'.",
      "The wizard walks you step-by-step: name → template → data → mapping → publish.",
      "Pick a template (your own, AI-generated, or from the Marketplace).",
      "Upload a CSV or generate rows with AI.",
      "Review variable mapping (auto-suggestions are provided).",
      "Choose publish mode (Draft/Live), pick the target website and click 'Generate'.",
    ],
    tips: [
      "Re-selecting a marketplace template never duplicates — it reuses the existing snapshot.",
      "Use the AI Campaign Assistant for naming, mapping and readiness checks.",
    ],
    guide: [
      { title: "Start the wizard", detail: "Campaigns → Create Campaign. A step-by-step wizard opens: Name → Template → Data → Mapping → Publish." },
      { title: "Name & type", detail: "Give the campaign a clear name and pick the campaign type (SEO / SEA / GEO). The type tunes how content is optimized." },
      { title: "Choose a template", detail: "Select one of your own templates, an AI-generated one, or import from the Marketplace. A live preview confirms your choice." },
      { title: "Add your data", detail: "Upload a CSV of rows (each row = one page) or generate rows with AI. Use a pipe (|) inside a cell for spintax variations." },
      { title: "Map variables", detail: "The wizard auto-suggests which CSV column fills each {variable}. Check the confidence badges and fix any unmapped variables flagged in the alert." },
      { title: "Set keyword source (optional)", detail: "Record whether keywords come from a New business or an Existing website so the source shows on the campaign detail later." },
      { title: "Choose publish mode", detail: "Pick Draft (safe review on the CMS) or Live. Then choose the target connected website." },
      { title: "Generate & monitor", detail: "Click Generate and watch live progress. Finished pages appear under Generated Pages and on the campaign detail view." },
    ],
  },
  {
    id: "pages", icon: Layers, group: "Core", name: "Generated Pages",
    short: "Every generated page in one place — search, filter and bulk actions.",
    steps: [
      "Open 'Pages' from the sidebar.",
      "Filter by campaign, status or website.",
      "Click a row to preview, edit or open it on the live CMS.",
      "Bulk select rows to republish, delete or export.",
      "Run the duplicate detector to surface near-identical content.",
    ],
  },
  {
    id: "templates", icon: FileText, group: "Core", name: "Templates",
    short: "Build your own templates, generate them with AI, or scan from a URL.",
    steps: [
      "'New Template' offers 4 options: Manual, AI Generate, Scan from URL, Import.",
      "AI Generate only needs business + niche + service — design and structure are auto-built.",
      "Scan extracts design and variables from any live page.",
      "Write variables in `{variable_name}` format using lowercase_snake_case.",
      "See results instantly in the live preview.",
    ],
    tips: ["Download the CSV starter for any template — it comes pre-filled with the right columns."],
    guide: [
      { title: "Open Templates", detail: "Sidebar → Templates. Click 'New Template' to see the four creation methods." },
      { title: "Pick a creation method", detail: "Manual (build from scratch), AI Generate (business + niche + service), Scan from URL (copy design from a live page), or Import (paste/upload existing HTML)." },
      { title: "Define your variables", detail: "Insert placeholders as {variable_name} using lowercase_snake_case, e.g. {city}, {service_name}. These become the columns you fill with data later." },
      { title: "Design the layout", detail: "Edit sections and styles. With AI Generate, the design and structure are built for you; with Scan, they are extracted from the source page." },
      { title: "Preview live", detail: "The live preview updates instantly and shows sample values in place of each variable so you can spot layout issues early." },
      { title: "Download the CSV starter", detail: "Use the CSV starter export — it comes pre-filled with a column for every variable so your data lines up perfectly." },
      { title: "Save", detail: "Save the template. It's now selectable in Campaigns and PGP Generate." },
    ],
  },
  {
    id: "marketplace", icon: Store, group: "Core", name: "Template Marketplace",
    short: "Browse community templates and import them with one click.",
    steps: [
      "Filter by category (WordPress / Shopify / Personal Portfolio etc.).",
      "Hover any card to see the preview and plan badge.",
      "Click 'Use Template' — progress shows download → adapt → save.",
      "If you have already imported it, the existing copy is reused (no duplicates).",
      "Version pinning keeps your copy stable even if the marketplace template updates.",
    ],
  },
  {
    id: "wp-control", icon: SlidersHorizontal, group: "Core", name: "WP Control",
    short: "Remote-manage your connected WordPress sites from one dashboard.",
    steps: [
      "Select a connected WordPress site.",
      "Check the connector plugin status and version (auto-update supported).",
      "Push layout, Elementor and critical-CSS settings to the site.",
      "Trigger content sync or re-publish without leaving the app.",
    ],
    tips: ["Keep the 3XVISIBILITY WordPress connector plugin updated for the best publishing fidelity."],
    guide: [
      { title: "Connect the site first", detail: "WP Control only lists WordPress sites already added under Websites with a valid Application Password." },
      { title: "Install / verify the connector plugin", detail: "Make sure the 3XVISIBILITY WordPress connector plugin is installed and active. WP Control shows its status and version." },
      { title: "Check for updates", detail: "If a newer plugin version exists, use the built-in auto-updater so publishing stays reliable." },
      { title: "Select a site", detail: "Choose the WordPress site you want to manage from the list." },
      { title: "Push settings", detail: "Send layout, Elementor container width and critical-CSS fallback settings straight to the site." },
      { title: "Sync or re-publish", detail: "Trigger a content sync or re-publish generated pages without opening the WordPress admin." },
      { title: "Confirm on the live site", detail: "Open the page on your CMS to confirm the design and content match the preview." },
    ],
  },
  {
    id: "data", icon: Database, group: "Core", name: "Data CSV",
    short: "Manage CSV data for variables and use AI to fill the gaps.",
    steps: [
      "Upload a CSV or build rows from scratch.",
      "Use AI to auto-fill empty cells.",
      "Add multi-value cells using a pipe (|) for variations.",
      "Save and use the dataset directly in any campaign.",
    ],
  },
  {
    id: "pgp-keywords", icon: KeyRound, group: "PGP Suite", name: "Keywords",
    short: "Manage keyword sets for programmatic SEO.",
    steps: [
      "Add keywords manually or import a CSV.",
      "Auto-extract keywords from a source URL.",
      "Assign keywords to content groups.",
    ],
  },
  {
    id: "pgp-generate", icon: Zap, group: "PGP Suite", name: "PGP Generate",
    short: "Spin up massive page sets from keyword combinations.",
    steps: [
      "Pick a template and a keyword set.",
      "Choose a generation method (all combos / sequential / random).",
      "Set the batch size and click 'Start' — live progress is shown.",
    ],
    tips: ["Templates are managed under 'Templates' in the main menu — the old 'Content Groups' has been merged there."],
  },
  {
    id: "pgp-terms", icon: Database, group: "PGP Suite", name: "Terms",
    short: "A master library of variable terms (city, service, niche, etc.).",
    steps: ["Create a term type.", "Add values to it.", "Get auto-suggestions whenever the term is used in templates."],
  },
  {
    id: "website-content", icon: Layers, group: "Discovery", name: "Website Content",
    short: "Discover, scan and SEO-optimize all pages and products on a connected site.",
    steps: [
      "Select the website.",
      "Click 'Scan' — existing content and design are extracted automatically.",
      "From any page row you can SEO-optimize, retranslate or rewrite content.",
      "Use AI to fill in missing meta tags.",
    ],
    tips: ["This replaces the old 'Scanner' and 'Discovery' tools — both are merged here."],
  },
  {
    id: "template-mapping", icon: Columns3, group: "Discovery", name: "Variable Mapping",
    short: "Map template variables to CSV columns or CMS fields.",
    steps: [
      "Pick a template and a data source.",
      "Accept the auto-mapping suggestion or adjust manually.",
      "Use the confidence indicator (high/medium/low) to make decisions.",
    ],
  },
  {
    id: "analytics", icon: BarChart3, group: "Analytics", name: "Analytics",
    short: "Overview of pages, traffic and conversions.",
    steps: ["Pick a date range.", "Review your top performing pages.", "Export to CSV when you need raw data."],
    guide: [
      { title: "Open Analytics", detail: "Sidebar → Analytics. The overview loads your workspace totals for pages, traffic and conversions." },
      { title: "Set the date range", detail: "Pick a start and end date (or a preset range). Every chart and table updates to that window." },
      { title: "Read the summary cards", detail: "The top cards show total pages, visits and conversion rate so you get the headline numbers at a glance." },
      { title: "Find top performers", detail: "Scan the top-pages table to see which generated pages bring the most traffic and where to double down." },
      { title: "Compare campaigns", detail: "Filter by campaign or website to see which effort is driving results." },
      { title: "Export raw data", detail: "Click Export to CSV when you need the numbers for a report or a spreadsheet." },
    ],
  },
  {
    id: "performance", icon: Activity, group: "Analytics", name: "Page Performance",
    short: "Per-page SEO score, load time and core web vitals.",
    steps: ["Select a page.", "Read the score breakdown and improvement tips.", "Run an AI fix in one click."],
  },
  {
    id: "content-calendar", icon: CalendarDays, group: "Analytics", name: "Content Calendar",
    short: "Schedule and plan future publishes.",
    steps: ["Pick a date.", "Drag a page or campaign onto the date.", "It auto-publishes at the scheduled time."],
  },
  {
    id: "seo-audit", icon: ClipboardCheck, group: "Analytics", name: "SEO Audit",
    short: "Site-wide SEO health check — duplicate content, missing meta, broken links.",
    steps: ["Pick a site.", "Click 'Run Audit'.", "Fix issues in priority order."],
  },
  {
    id: "indexing", icon: Search, group: "Analytics", name: "Google Indexing",
    short: "Submit generated pages directly to Google.",
    steps: ["Connect Google Search Console.", "Select pages and click 'Submit for indexing'."],
  },
  {
    id: "affiliate", icon: Gift, group: "Account", name: "Affiliate",
    short: "Share your referral link and earn commission.",
    steps: ["Copy your unique link.", "Share it with friends or clients.", "Track earnings on the dashboard."],
  },
  {
    id: "referral", icon: Link2, group: "Account", name: "Referral",
    short: "Invite users with a tracked link and earn reward credits when they join.",
    steps: [
      "Copy your referral link from the Referral page.",
      "Share it — every signup and conversion is tracked automatically.",
      "Earned reward credits are applied to your account.",
    ],
    tips: ["Affiliate pays cash commission; Referral rewards you with in-app credits — you can use both."],
    guide: [
      { title: "Open Referral", detail: "Sidebar → Referral. Your unique tracked referral link is shown at the top." },
      { title: "Copy your link", detail: "Click Copy. The link carries your referral code so every visit is attributed to you." },
      { title: "Share it", detail: "Send the link to friends, clients or your audience — social, email or a blog all work." },
      { title: "Track signups", detail: "Each click, signup and conversion is recorded automatically and shown on the page." },
      { title: "Earn reward credits", detail: "When a referred user converts, reward credits are added to your account per the reward settings." },
      { title: "Spend the credits", detail: "Use the earned credits toward AI generations and other in-app usage." },
    ],
  },
  {
    id: "billing", icon: CreditCard, group: "Account", name: "Billing",
    short: "Plan upgrades, invoices and payment methods.",
    steps: ["Review your current plan.", "Upgrade or downgrade.", "Use the Stripe portal to download invoices."],
    guide: [
      { title: "Open Billing", detail: "Sidebar → Billing. Your current plan, usage limits and remaining AI credits are shown at the top." },
      { title: "Compare plans", detail: "Review Free, Starter, Pro and Agency. Each lists its template limit, page limit, AI credits and team features." },
      { title: "Choose a plan", detail: "Click Upgrade (or downgrade) on the plan that fits. Pro/Agency unlock unlimited templates and team collaboration." },
      { title: "Pay securely", detail: "Checkout is handled by Stripe. Enter your card details on the secure Stripe page — the app never stores your card." },
      { title: "Confirm activation", detail: "After payment you return to the app and the new limits apply immediately. A success message confirms the upgrade." },
      { title: "Manage payment & invoices", detail: "Use the Stripe customer portal to update your card, change the plan, or download past invoices." },
      { title: "Watch your usage", detail: "Track page and AI-credit usage on Billing so you upgrade before hitting a limit." },
    ],
  },
  {
    id: "settings", icon: Settings, group: "Account", name: "Settings",
    short: "Profile, language, theme and notifications.",
    steps: ["Update profile info.", "Switch language (29 supported).", "Set notification preferences."],
  },
  {
    id: "workspace-settings", icon: Users, group: "Account", name: "Workspace Settings",
    short: "Invite team members and manage roles (Pro/Agency only).",
    steps: ["Click 'Invite Member'.", "Set the email and role (admin/editor/viewer).", "Review every action in the audit log."],
  },
];

const GROUPS = ["Core", "PGP Suite", "Discovery", "Analytics", "Account"] as const;
const QUICK_FLOW = [
  { step: 1, title: "Connect a website", desc: "Sidebar → Websites → Add → enter credentials." },
  { step: 2, title: "Build or import a template", desc: "Pick a ready design from Templates or the Marketplace." },
  { step: 3, title: "Add data", desc: "Upload a CSV or generate rows with AI." },
  { step: 4, title: "Run the campaign", desc: "Map variables and click 'Generate' — pages go straight to your site." },
];

interface Integration {
  name: string;
  connects: string;
  used: string;
  how: string;
}

const INTEGRATIONS: Integration[] = [
  {
    name: "WordPress",
    connects: "Websites · WP Control",
    used: "Publish generated pages, sync content, remote-manage the site",
    how: "Install the 3XVISIBILITY connector plugin, then add the site with an Application Password.",
  },
  {
    name: "WooCommerce",
    connects: "Websites · Campaigns",
    used: "Publish product & category landing pages on a WordPress store",
    how: "Connect the WordPress site first; WooCommerce is detected automatically.",
  },
  {
    name: "Shopify",
    connects: "Websites · Website Content",
    used: "Sync products, bulk SEO, publish pages to your store",
    how: "Use the one-click Shopify OAuth flow (Connect Shopify) — no manual keys needed.",
  },
  {
    name: "PrestaShop",
    connects: "Websites · Campaigns",
    used: "Publish pages and product content to a PrestaShop store",
    how: "Add the site URL and API key under Websites → Add.",
  },
  {
    name: "Google Search Console",
    connects: "Indexing · SEO Audit",
    used: "Submit generated pages to Google for faster indexing",
    how: "Connect a Google service account, then submit pages from the Indexing page.",
  },
  {
    name: "AI (Gemini)",
    connects: "AI Site Builder · Templates · Campaigns · Data CSV",
    used: "Generate designs, copy, images, keywords and fill missing data",
    how: "Built in — no API key required. Light tasks use the cheapest model to save credits.",
  },
  {
    name: "Stripe (Billing)",
    connects: "Billing",
    used: "Plan upgrades, invoices and payment methods",
    how: "Managed for you — upgrade from Billing and use the portal for invoices.",
  },
];

interface ConnectField {
  label: string;
  desc: string;
}

interface ConnectTutorial {
  id: string;
  name: string;
  icon: React.ElementType;
  intro: string;
  fields: ConnectField[];
  permissions: string[];
  test: string[];
  troubleshoot?: string[];
}

const CONNECT_TUTORIALS: ConnectTutorial[] = [
  {
    id: "connect-wordpress",
    name: "Connect WordPress (self-hosted)",
    icon: Globe,
    intro: "Publish and sync pages to your own WordPress site using a secure Application Password. Works with WordPress 5.6+ over HTTPS.",
    fields: [
      { label: "Site URL", desc: "Your full site address, e.g. https://yoursite.com — include https:// and the www prefix only if your site uses it." },
      { label: "Username", desc: "The WordPress admin/editor username the pages will be published as." },
      { label: "Application Password", desc: "A dedicated password (not your login password). Create it in WordPress: Users → Profile → Application Passwords → enter a name → Add New." },
      { label: "Connector plugin", desc: "Install & activate the 3XVISIBILITY WordPress connector plugin for best publishing fidelity (Elementor, critical CSS, media)." },
    ],
    permissions: [
      "The account must have Editor or Administrator role to create and update pages.",
      "Pretty permalinks must be enabled (Settings → Permalinks → anything except 'Plain') so the REST API works.",
      "The site must be served over HTTPS — Application Passwords are disabled on plain HTTP.",
    ],
    test: [
      "Go to Websites → + Add Website → choose WordPress.",
      "Fill in Site URL, Username and Application Password.",
      "Click 'Test Connection'.",
      "A green tick means it worked — click Save. Content from the site is then pulled in automatically.",
    ],
    troubleshoot: [
      "SSL / SNI error → check whether the URL needs (or must drop) the www prefix; if it persists, contact your host.",
      "'rest_no_route' error → enable pretty permalinks in WordPress.",
      "401 Unauthorized → regenerate the Application Password and make sure you copied it without spaces.",
    ],
  },
  {
    id: "connect-shopify",
    name: "Connect Shopify",
    icon: Store,
    intro: "Connect your Shopify store with a one-click OAuth flow — no manual API keys to copy. Once connected you can sync products, run bulk SEO and publish pages.",
    fields: [
      { label: "Store domain", desc: "Your myshopify domain, e.g. your-store.myshopify.com (used to start the OAuth handshake)." },
      { label: "Connect button", desc: "Click 'Connect Shopify' — you're redirected to Shopify to log in and approve access. No keys are entered by hand." },
    ],
    permissions: [
      "You must be the store owner or a staff account with app-install permission.",
      "On the Shopify approval screen, grant access to Products and Content so the app can read/write product and page data.",
      "Access is per-user and revocable at any time from Shopify → Settings → Apps and sales channels.",
    ],
    test: [
      "Go to Websites → + Add Website → choose Shopify (or open the Shopify guide page).",
      "Enter your .myshopify.com domain and click 'Connect Shopify'.",
      "Approve the requested permissions on Shopify's screen.",
      "You're returned to the app with a connected status — products appear under Website Content once synced.",
    ],
    troubleshoot: [
      "Redirect fails or 'app not found' → confirm the store domain is spelled correctly and ends in .myshopify.com.",
      "Permissions error later → reconnect and make sure Products & Content scopes are approved.",
    ],
  },
  {
    id: "connect-gsc",
    name: "Connect Google Search Console",
    icon: Search,
    intro: "Connect Google Search Console to submit generated pages to Google and monitor indexing. Uses a Google service account with access to your verified property.",
    fields: [
      { label: "Property (site URL)", desc: "The exact verified property from Search Console — either a Domain property (sc-domain:example.com) or a URL-prefix (https://example.com/). Pick it from the list; don't type a random URL." },
      { label: "Service account JSON", desc: "The credentials key file for a Google Cloud service account. Paste/upload it in Websites settings — it is stored securely and never shown in the browser." },
    ],
    permissions: [
      "The property must already be verified in Google Search Console.",
      "Add the service account email as a user on the property: Search Console → Settings → Users and permissions → Add user (Full or Owner).",
      "Enable the 'Google Search Console API' (and Indexing API for submissions) in the Google Cloud project.",
    ],
    test: [
      "Connect the Google service account under Websites / SEO settings.",
      "Open the Indexing page — your verified properties load in the selector.",
      "Select a property; if pages list without a 403, the connection works.",
      "Select pages and click 'Submit for indexing' to send them to Google.",
    ],
    troubleshoot: [
      "403 on a property → the service account isn't added as a user, or the property isn't verified.",
      "Empty property list → confirm the property exists and is verified in Search Console for that Google account.",
    ],
  },
];



export default function DocumentationPage() {
  const [active, setActive] = useState<string>("getting-started");
  const pageRef = useRef<HTMLDivElement>(null);
  usePageAutoTranslate(pageRef, [active]);

  useEffect(() => {
    document.title = "Documentation — 3XVISIBILITY";
    const m = document.querySelector('meta[name="description"]');
    if (m) m.setAttribute("content", "Complete guide to 3XVISIBILITY tools — learn how to use campaigns, templates, websites and AI features.");
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground" ref={pageRef}>
      <Seo
        title="Documentation"
        description="Step-by-step guides for every 3XVISIBILITY tool — from connecting websites and building templates to generating and publishing pages at scale."
        path="/docs"
      />
      <LandingNav />

      <main className="container mx-auto px-4 lg:px-8 pt-28 pb-16" data-auto-translate>
        {/* Hero */}
        <header className="max-w-3xl mx-auto text-center mb-12">
          <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">
            <BookOpen className="h-3 w-3 mr-1" /> Documentation
          </Badge>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">
            Complete guide to every tool
          </h1>
          <p className="text-base md:text-lg text-muted-foreground">
            Step-by-step instructions for every feature in your workspace.
          </p>
        </header>

        <div className="grid lg:grid-cols-[240px_1fr] gap-8">
          {/* Sidebar TOC */}
          <aside className="lg:sticky lg:top-24 lg:self-start">
            <nav className="space-y-1 text-sm">
              <a href="#getting-started" onClick={() => setActive("getting-started")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "getting-started" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                🚀 Getting Started
              </a>
              {GROUPS.map((g) => (
                <a key={g} href={`#group-${g.replace(/\s+/g, "-").toLowerCase()}`}
                  onClick={() => setActive(g)}
                  className={`block px-3 py-2 rounded-md transition-colors ${active === g ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                  {g}
                </a>
              ))}
              <a href="#integrations" onClick={() => setActive("integrations")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "integrations" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                🔌 Integrations
              </a>
              <a href="#faq" onClick={() => setActive("faq")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "faq" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                ❓ FAQ
              </a>
            </nav>
          </aside>

          {/* Content */}
          <div className="space-y-12 min-w-0">
            {/* Getting Started */}
            <section id="getting-started" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <Rocket className="h-6 w-6 text-primary" /> Getting Started — 4 quick steps
              </h2>
              <p className="text-muted-foreground mb-6">
                New here? Follow this sequence and your first batch of pages will be live in about 10 minutes.
              </p>
              <ol className="space-y-3">
                {QUICK_FLOW.map((s) => (
                  <li key={s.step} className="flex gap-4 p-4 rounded-lg border border-border bg-card">
                    <div className="flex-shrink-0 h-8 w-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-sm">
                      {s.step}
                    </div>
                    <div>
                      <div className="font-semibold">{s.title}</div>
                      <div className="text-sm text-muted-foreground mt-0.5">{s.desc}</div>
                    </div>
                  </li>
                ))}
              </ol>
            </section>

            {/* Tool groups */}
            {GROUPS.map((group) => (
              <section key={group} id={`group-${group.replace(/\s+/g, "-").toLowerCase()}`} className="scroll-mt-24">
                <h2 className="text-2xl font-bold mb-6 border-b border-border pb-2">{group}</h2>
                <div className="space-y-6">
                  {TOOLS.filter((t) => t.group === group).map((tool) => {
                    const Icon = tool.icon;
                    return (
                      <article key={tool.id} id={tool.id} className="scroll-mt-24 rounded-xl border border-border bg-card p-5 md:p-6">
                        <header className="flex items-start gap-3 mb-3">
                          <div className="h-10 w-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center flex-shrink-0">
                            <Icon className="h-5 w-5" />
                          </div>
                          <div className="min-w-0">
                            <h3 className="font-semibold text-lg">{tool.name}</h3>
                            <p className="text-sm text-muted-foreground mt-0.5">{tool.short}</p>
                          </div>
                        </header>

                        <div className="ml-0 md:ml-13">
                          <h4 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-2 mt-4">
                            How to use it
                          </h4>
                          <ol className="space-y-1.5">
                            {tool.steps.map((s, i) => (
                              <li key={i} className="flex gap-2 text-sm">
                                <CheckCircle2 className="h-4 w-4 text-primary flex-shrink-0 mt-0.5" />
                                <span>{s}</span>
                              </li>
                            ))}
                          </ol>

                          {tool.guide && tool.guide.length > 0 && (
                            <details className="mt-4 rounded-md border border-primary/20 bg-primary/5 p-3 group/guide" open>
                              <summary className="flex items-center gap-1.5 text-xs font-semibold text-primary mb-1 cursor-pointer list-none">
                                <BookOpen className="h-3.5 w-3.5" /> Detailed step-by-step guide
                              </summary>
                              <ol className="mt-3 space-y-3">
                                {tool.guide.map((g, i) => (
                                  <li key={i} className="flex gap-3">
                                    <div className="flex-shrink-0 h-6 w-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-xs">
                                      {i + 1}
                                    </div>
                                    <div className="min-w-0">
                                      <div className="text-sm font-semibold">{g.title}</div>
                                      <div className="text-sm text-muted-foreground mt-0.5">{g.detail}</div>
                                    </div>
                                  </li>
                                ))}
                              </ol>
                            </details>
                          )}



                          {tool.tips && tool.tips.length > 0 && (
                            <div className="mt-4 rounded-md bg-amber-500/5 border border-amber-500/20 p-3">
                              <div className="flex items-center gap-1.5 text-xs font-semibold text-amber-600 dark:text-amber-400 mb-1">
                                <Lightbulb className="h-3.5 w-3.5" /> Tips
                              </div>
                              <ul className="space-y-1 text-xs text-muted-foreground">
                                {tool.tips.map((tip, i) => <li key={i}>• {tip}</li>)}
                              </ul>
                            </div>
                          )}
                        </div>
                      </article>
                    );
                  })}
                </div>
              </section>
            ))}

            {/* Integrations */}
            <section id="integrations" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <Plug className="h-6 w-6 text-primary" /> Integrations &amp; Connections
              </h2>
              <p className="text-muted-foreground mb-6">
                What connects with what — and how each connection is used across the app.
              </p>
              <div className="space-y-4">
                {INTEGRATIONS.map((it) => (
                  <div key={it.name} className="rounded-xl border border-border bg-card p-5">
                    <div className="flex flex-wrap items-center gap-2 mb-2">
                      <h3 className="font-semibold text-lg">{it.name}</h3>
                      <Badge variant="secondary" className="text-xs">{it.connects}</Badge>
                    </div>
                    <p className="text-sm mb-1"><span className="font-medium">Used for: </span><span className="text-muted-foreground">{it.used}</span></p>
                    <p className="text-sm"><span className="font-medium">How to connect: </span><span className="text-muted-foreground">{it.how}</span></p>
                  </div>
                ))}
              </div>
            </section>

            {/* Connection tutorials */}
            <section id="connect-tutorials" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <Plug className="h-6 w-6 text-primary" /> Connection tutorials
              </h2>
              <p className="text-muted-foreground mb-6">
                Full walkthroughs for connecting WordPress, Shopify and Google Search Console — input fields, permissions and how to test the connection.
              </p>
              <div className="space-y-6">
                {CONNECT_TUTORIALS.map((t) => {
                  const Icon = t.icon;
                  return (
                    <article key={t.id} id={t.id} className="scroll-mt-24 rounded-xl border border-border bg-card p-5 md:p-6">
                      <header className="flex items-start gap-3 mb-3">
                        <div className="h-10 w-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center flex-shrink-0">
                          <Icon className="h-5 w-5" />
                        </div>
                        <div className="min-w-0">
                          <h3 className="font-semibold text-lg">{t.name}</h3>
                          <p className="text-sm text-muted-foreground mt-0.5">{t.intro}</p>
                        </div>
                      </header>

                      <div className="space-y-4 mt-4">
                        {/* Input fields */}
                        <div>
                          <h4 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-2">
                            Input fields
                          </h4>
                          <ul className="space-y-2">
                            {t.fields.map((f, i) => (
                              <li key={i} className="text-sm">
                                <span className="font-semibold">{f.label}</span>
                                <span className="text-muted-foreground"> — {f.desc}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        {/* Permissions */}
                        <div>
                          <h4 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-2">
                            Permissions required
                          </h4>
                          <ul className="space-y-1.5">
                            {t.permissions.map((p, i) => (
                              <li key={i} className="flex gap-2 text-sm">
                                <CheckCircle2 className="h-4 w-4 text-primary flex-shrink-0 mt-0.5" />
                                <span>{p}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        {/* Test connection */}
                        <div>
                          <h4 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-2">
                            Test the connection
                          </h4>
                          <ol className="space-y-3">
                            {t.test.map((s, i) => (
                              <li key={i} className="flex gap-3">
                                <div className="flex-shrink-0 h-6 w-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-xs">
                                  {i + 1}
                                </div>
                                <span className="text-sm mt-0.5">{s}</span>
                              </li>
                            ))}
                          </ol>
                        </div>

                        {/* Troubleshooting */}
                        {t.troubleshoot && t.troubleshoot.length > 0 && (
                          <div className="rounded-md bg-amber-500/5 border border-amber-500/20 p-3">
                            <div className="flex items-center gap-1.5 text-xs font-semibold text-amber-600 dark:text-amber-400 mb-1">
                              <AlertCircle className="h-3.5 w-3.5" /> Troubleshooting
                            </div>
                            <ul className="space-y-1 text-xs text-muted-foreground">
                              {t.troubleshoot.map((tip, i) => <li key={i}>• {tip}</li>)}
                            </ul>
                          </div>
                        )}
                      </div>
                    </article>
                  );
                })}
              </div>
            </section>

            {/* FAQ */}
            <section id="faq" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-6 border-b border-border pb-2 flex items-center gap-2">
                <AlertCircle className="h-6 w-6 text-primary" /> FAQ
              </h2>
              <div className="space-y-4">
                {[
                  { q: "How are AI credits kept low?", a: "Light tasks always use Gemini Flash Lite (the cheapest model). Images fall back to Unsplash and translations to LibreTranslate whenever possible." },
                  { q: "If a marketplace template is updated, do my pages change?", a: "No. Version pinning saves your copy as a snapshot — marketplace updates do not affect it." },
                  { q: "Getting an SSL error when connecting WordPress?", a: "Check whether the site URL needs the www prefix. If it is an SNI mismatch, contact your hosting provider." },
                  { q: "Where do I upgrade my plan?", a: "Sidebar → Billing → Upgrade plan. Pro/Agency unlock more templates, credits and team features." },
                  { q: "Can a bulk delete be undone?", a: "No — bulk delete is permanent. Always read the confirmation dialog carefully." },
                ].map((f, i) => (
                  <details key={i} className="rounded-lg border border-border bg-card p-4 group">
                    <summary className="font-medium cursor-pointer list-none flex items-center justify-between">
                      <span>{f.q}</span>
                      <ArrowRight className="h-4 w-4 text-muted-foreground group-open:rotate-90 transition-transform" />
                    </summary>
                    <p className="mt-3 text-sm text-muted-foreground">{f.a}</p>
                  </details>
                ))}
              </div>
            </section>

            {/* CTA */}
            <section className="rounded-xl border border-primary/20 bg-gradient-to-br from-primary/10 to-transparent p-6 md:p-8 text-center">
              <h2 className="text-xl font-bold mb-2">Still have questions?</h2>
              <p className="text-sm text-muted-foreground mb-4">Open the app and try it directly — every page has contextual help built in.</p>
              <Button asChild>
                <Link to="/dashboard">Go to the app <ArrowRight className="ml-2 h-4 w-4" /></Link>
              </Button>
            </section>
          </div>
        </div>
      </main>

      <LandingFooter />
    </div>
  );
}
