import { Seo } from "@/components/Seo";
import { Link } from "react-router-dom";
import { useEffect, useState, useRef, useMemo } from "react";
import { usePageAutoTranslate } from "@/i18n/usePageAutoTranslate";
import { useLanguage } from "@/i18n/LanguageContext";
import { supabase } from "@/integrations/supabase/client";
import {
  LayoutDashboard, Globe, Rocket, Layers, FileText, Store, Database,
  KeyRound, Zap, Columns3, BarChart3, Activity, CalendarDays,
  ClipboardCheck, Search, Gift, CreditCard, Settings, Users,
  ArrowRight, BookOpen, CheckCircle2, Lightbulb, AlertCircle,
  Sparkles, SlidersHorizontal, Link2, Plug, HelpCircle, Loader2, GripVertical, Eye, History as HistoryIcon, RotateCcw,
} from "lucide-react";
import { toast } from "sonner";
import { LandingNav } from "@/components/landing/LandingNav";
import { LandingFooter } from "@/components/landing/LandingFooter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";


interface GuideStep {
  title: string;
  detail: string;
}

interface ToolDoc {
  id: string;
  icon: React.ElementType;
  name: string;
  group: string;
  short: string;
  steps: string[];
  tips?: string[];
  /** Optional in-depth, numbered walkthrough shown below the quick steps. */
  guide?: GuideStep[];
}


const TOOLS: ToolDoc[] = [
  {
    id: "dashboard", icon: LayoutDashboard, group: "Core", name: "Dashboard",
    short: "All workspace activity, recent campaigns and quick stats in one place.",
    steps: [
      "After login you land on the Dashboard by default.",
      "Top cards show total campaigns, generated pages and connected websites.",
      "Click any recent campaign card to jump straight into its detail view.",
      "Quick action buttons let you create a new campaign or template.",
    ],
    tips: ["On day one, start with 'Connect Website' from here."],
  },
  {
    id: "websites", icon: Globe, group: "Core", name: "Websites",
    short: "Connect WordPress, WooCommerce, Shopify and PrestaShop sites.",
    steps: [
      "Click the '+ Add Website' button.",
      "Pick your platform (WordPress / Shopify / WooCommerce / PrestaShop).",
      "Enter the site URL and credentials (App Password / API key).",
      "Hit 'Test Connection' — a green tick means you can save.",
      "Content from the connected site will be pulled in automatically.",
    ],
    tips: [
      "For WordPress, always use an Application Password — never the regular password.",
      "If you see an SSL error, check whether the URL needs www or not.",
    ],
  },
  {
    id: "ai-site-builder", icon: Sparkles, group: "Core", name: "AI Site Builder",
    short: "Describe your business and get a full multi-page site design generated by AI.",
    steps: [
      "Sidebar → AI Site Builder.",
      "Enter business name, niche, services + a short description of your customer.",
      "Pick a brand vibe — the color palette, fonts and section rhythm lock before generation.",
      "AI builds the full multi-page site (hero, features, services, testimonials, FAQ, contact) with matching copy and images in one pass.",
      "Regenerate any single section without rebuilding the whole site.",
      "Send the result to Templates or publish straight to a connected website.",
    ],
    tips: [
      "Images use Unsplash first and fall back to AI generation only when needed — this keeps credits low.",
      "Save your business/niche/service combo as an AI Preset (localStorage) for one-click reload later.",
    ],
    guide: [
      { title: "Open the builder", detail: "Sidebar → AI Site Builder." },
      { title: "Describe your business", detail: "Type the business name, niche/industry and the services or products you offer. The more specific you are, the better the copy." },
      { title: "Language & location (optional)", detail: "Pick the primary language and target country so tone and copy match your audience." },
      { title: "Pick a brand vibe", detail: "Choose from the rotating vibe palettes — this locks the color palette, fonts and layout before generation." },
      { title: "Generate", detail: "Click Generate. Every page is built in one pass with copy and images." },
      { title: "Review & refine", detail: "Use per-section regenerate to redo just one block instead of the whole site." },
      { title: "Save or publish", detail: "Send to Templates to reuse in campaigns, or publish directly to a connected website." },
    ],
  },
  {
    id: "campaigns", icon: Rocket, group: "Core", name: "Campaigns",
    short: "Bulk-generate and publish pages by combining a Keyword Group with Locations + Business Info.",
    steps: [
      "Best flow: build a Keyword Group first (template + language + terms/variables), then click 'Generate campaign' from it — the wizard opens pre-filled.",
      "Wizard steps: Name & type → Locations → Business Info → Zip/Cross pairing → Review → Generate.",
      "Locations step pulls city/region/country from the Location Database (with server-side search).",
      "Business Info step fills brand_name, phone, email, address, etc. — used wherever those variables appear in the template.",
      "Zip mode = 5 cities → exactly 5 pages (paired 1:1). Cross mode = Cartesian product.",
      "Live pairing preview shows which row becomes which page before you generate.",
      "Live progress bar + per-row status (queued → generating → success/failed) while the batch runs.",
    ],
    tips: [
      "Variable priority: Locations > Business Info > AI-generated content > Keyword Group defaults.",
      "Publishing pushes the final interpolated content — no placeholders leak to the live site.",
      "Duplicate slugs? Use Auto-fix + Diversity Repair (temp 0.95) for unique content per page.",
    ],
    guide: [
      { title: "Start from a Keyword Group", detail: "Sidebar → Keywords → Keyword Groups → your saved group → 'Generate campaign'. The wizard opens with template, language, terms and variables already filled." },
      { title: "Name & type", detail: "Give the campaign a clear name and pick SEO / SEA / GEO. The type tunes optimization." },
      { title: "Locations", detail: "Add countries, regions and cities from the Location Database. Use the Bulk City Loader if a country is missing cities. These override any placeholder geo values." },
      { title: "Business Info", detail: "Fill brand name, phone, email, address, hours. Whichever variables appear in the template are replaced with these values." },
      { title: "Zip vs Cross", detail: "Zip = 1:1 pairing (N cities × N services → N pages). Cross = every combination. Live preview table shows the exact pairing." },
      { title: "Review", detail: "Variable checklist confirms every {variable} has a source. Any red row = unmapped, fix before continuing." },
      { title: "Generate & monitor", detail: "Click Generate. Watch the live progress bar and publish log; failed rows can be retried individually. Client-side batching keeps the request from hitting 504 timeouts." },
    ],
  },

  {
    id: "pages", icon: Layers, group: "Core", name: "Generated Pages",
    short: "Every generated page in one place — search, filter and bulk actions.",
    steps: [
      "Open 'Pages' from the sidebar.",
      "Filter by campaign, status or website.",
      "Click a row to preview, edit or open it on the live CMS.",
      "Bulk select rows to republish, delete or export.",
      "Run the duplicate detector to surface near-identical content.",
    ],
  },
  {
    id: "templates", icon: FileText, group: "Core", name: "Templates",
    short: "Build, AI-generate or scan templates and add variables in one click.",
    steps: [
      "'New Template' offers 4 options: Manual, AI Generate, Scan from URL, Import.",
      "AI Generate only needs business + niche + service — design and structure are auto-built.",
      "Scan extracts design AND variables from any live page (public rendered HTML).",
      "'AI Add Variables' scans your HTML and injects {variable_name} placeholders — including brand_name, phone, address, testimonial company/location.",
      "Section-scoped rewrite: regenerate only Services / FAQ / Testimonials / About without touching the rest.",
      "Download a per-template CSV starter (columns already match every variable).",
    ],
    tips: [
      "Variables use lowercase_snake_case and the {variable} syntax. Global business variables (brand_name, phone, email, address) are recognized automatically.",
      "Design Preservation Rule: AI never changes HTML wrappers, CSS classes, IDs or <style> blocks — only the text content and image sources.",
    ],
    guide: [
      { title: "Open Templates", detail: "Sidebar → Templates → New Template." },
      { title: "Pick a creation method", detail: "Manual, AI Generate, Scan from URL, or Import (paste/upload HTML)." },
      { title: "Add variables", detail: "Insert {variable_name} manually, or click 'AI Add Variables' to auto-inject placeholders across headings, body, testimonials and CTAs." },
      { title: "Section-scoped rewrite (optional)", detail: "Open the SEO Optimize dialog and choose a section (Services / FAQ / Testimonials / About) to regenerate only that block." },
      { title: "Preview live", detail: "The preview shows sample values in place of every variable so layout issues surface early." },
      { title: "CSV starter", detail: "Click 'Download CSV starter' — the file has one column per variable, ready for data." },
      { title: "Save", detail: "The template is now selectable in Keyword Groups and Campaigns." },
    ],
  },
  {
    id: "marketplace", icon: Store, group: "Core", name: "Template Marketplace",
    short: "Import community templates in Elementor, Shopify or HTML/CSS format.",
    steps: [
      "Filter by category (Consulting / SaaS / WordPress / Shopify / Portfolio, etc.).",
      "Pick a target format: Elementor, Shopify, or HTML/CSS — the same template ships in all three.",
      "Click 'Use Template' — progress shows download → adapt → save.",
      "Optional: toggle 'Auto-run AI Add Variables' so the imported template gets variables in the same step.",
      "Version pinning keeps your copy stable even if the marketplace template updates.",
    ],
    tips: [
      "Re-selecting a marketplace template never duplicates — the existing snapshot is reused.",
      "8 rotating vibe palettes are applied on import so no two marketplace-based sites look identical.",
    ],
  },
  {
    id: "wp-control", icon: SlidersHorizontal, group: "Core", name: "WP Control",
    short: "Remote-manage connected WordPress sites (v1.3.5+ connector plugin).",
    steps: [
      "Select a connected WordPress site.",
      "Check the connector plugin status (auto-updater built in from v1.3.5+).",
      "Push layout, Elementor container width and critical-CSS fallback to the site.",
      "Trigger content sync or re-publish without leaving the app.",
      "Elementor metadata is cleared on publish so SEO optimizations propagate to the live page.",
    ],
    tips: ["Keep the 3XVISIBILITY WordPress connector plugin updated — publishing fidelity depends on it."],
  },
  {
    id: "data", icon: Database, group: "Core", name: "Data CSV",
    short: "Manage CSV data for variables and use AI to fill the gaps.",
    steps: [
      "Upload a CSV or build rows from scratch.",
      "Use AI to auto-fill empty cells (per-row mode = unique content per page).",
      "Add multi-value cells using a pipe (|) for spintax variations.",
      "Save and use the dataset directly in any campaign.",
    ],
  },
  {
    id: "pgp-keywords", icon: KeyRound, group: "PGP Suite", name: "Keywords",
    short: "Extract keywords from templates or websites — no global auto-generation.",
    steps: [
      "Add keywords manually, from a template's variables, from a connected website, or from any URL.",
      "Pick the target language (30+ supported) — keywords are generated in that language.",
      "One-click 'Auto-link keywords' matches keywords to template variables.",
      "Set 'Terms per variable' — e.g. 5 = exactly 5 terms per variable.",
    ],
  },
  {
    id: "keyword-groups", icon: Layers, group: "PGP Suite", name: "Keyword Groups",
    short: "Reusable bundle of template + language + terms + variables — the entry point for Campaigns.",
    steps: [
      "Sidebar → Keywords → Keyword Groups → New Group.",
      "Step 1: pick a template + language + business/niche context.",
      "Step 2: add variable hints and set terms-per-variable (e.g. 5 terms each).",
      "Save — the group is stored in pgp_keyword_groups and available in the sidebar list.",
      "Click 'Generate campaign' from any saved group — the Campaign Wizard opens pre-filled; you only add Locations + Business Info.",
    ],
    tips: [
      "Keyword Groups intentionally EXCLUDE geographic + business info variables — those are set per-campaign under Locations and Business Info.",
      "Variable priority at generate time: Locations > Business Info > AI content > Keyword Group defaults.",
    ],
  },
  {
    id: "pgp-generate", icon: Zap, group: "PGP Suite", name: "PGP Generate",
    short: "Legacy generator — most flows now start from Keyword Groups → Campaign.",
    steps: [
      "Pick a template and a keyword set.",
      "Choose a generation method (all combos / sequential / random).",
      "Set the batch size and click 'Start' — live progress is shown.",
    ],
    tips: ["Prefer the Keyword Groups → Campaign flow — it wires Locations + Business Info automatically."],
  },
  {
    id: "pgp-terms", icon: Database, group: "PGP Suite", name: "Terms",
    short: "A master library of variable terms (city, service, niche, etc.).",
    steps: ["Create a term type.", "Add values to it.", "Get auto-suggestions whenever the term is used in templates."],
  },
  {
    id: "locations", icon: Globe, group: "PGP Suite", name: "Location Database",
    short: "Country → Region → City hierarchy with server-side search and bulk city loader.",
    steps: [
      "Open the Location Database dialog from any campaign or from Locations.",
      "Search countries/regions/cities — pagination and pg_trgm indexes keep it fast even at 250k+ rows.",
      "Missing cities for a country? Click 'Load ALL {Country} cities (global DB)' — pulls from CountriesNow + GeoNames + cities500.",
      "'Re-run city loader' opens the Bulk City Loader with multi-select countries, live progress, 3× auto-retry and CSV export of the result.",
    ],
    tips: ["Radius filtering + demographic enrichment let you scope campaigns to a distance from a city."],
  },
  {
    id: "website-content", icon: Layers, group: "Discovery", name: "Website Content",
    short: "Discover, scan and SEO-optimize all pages and products on a connected site.",
    steps: [
      "Select the website.",
      "Click 'Scan' — existing content and design are extracted automatically.",
      "From any page row: SEO-optimize (rewrites title + meta + full body content while preserving length), retranslate, or rewrite.",
      "Use 'Spin Content' for unique paraphrases per page (Gemini temp 1.0, HTML preserved).",
      "Force republish toggle clears caches so optimizations show live immediately.",
    ],
    tips: ["This replaces the old 'Scanner' and 'Discovery' tools — both are merged here."],
  },
  {
    id: "seo-optimize", icon: Sparkles, group: "Discovery", name: "SEO Analysis & AI Fix",
    short: "Multi-pass AI Fix loop that raises every factor to 80+ without regressing scores.",
    steps: [
      "Open any page's SEO Analysis dialog.",
      "Live factor scores show every sub-score with color-coded progress bars, updating in real time.",
      "Click 'AI Fix All' — up to 8 passes target only factors below 80.",
      "Deterministic polish forces meta description length, keyword presence, headings, word count, internal links and schema when AI misses them.",
      "Best-snapshot tracker guarantees scores never drop — a pass is discarded if the overall rank decreases.",
    ],
    tips: [
      "Fields already scoring ≥80 are preserved (never regenerated).",
      "SEA/GEO signals (trust/pricing/location/coverage keywords) are injected into the body so all three list-level badges improve together.",
    ],
  },
  {
    id: "template-mapping", icon: Columns3, group: "Discovery", name: "Variable Mapping",
    short: "Map template variables to CSV columns or CMS fields.",
    steps: [
      "Pick a template and a data source.",
      "Accept the auto-mapping suggestion or adjust manually.",
      "Use the confidence indicator (high/medium/low) to make decisions.",
    ],
  },

  {
    id: "analytics", icon: BarChart3, group: "Analytics", name: "Analytics",
    short: "Overview of pages, traffic and conversions.",
    steps: ["Pick a date range.", "Review your top performing pages.", "Export to CSV when you need raw data."],
    guide: [
      { title: "Open Analytics", detail: "Sidebar → Analytics. The overview loads your workspace totals for pages, traffic and conversions." },
      { title: "Set the date range", detail: "Pick a start and end date (or a preset range). Every chart and table updates to that window." },
      { title: "Read the summary cards", detail: "The top cards show total pages, visits and conversion rate so you get the headline numbers at a glance." },
      { title: "Find top performers", detail: "Scan the top-pages table to see which generated pages bring the most traffic and where to double down." },
      { title: "Compare campaigns", detail: "Filter by campaign or website to see which effort is driving results." },
      { title: "Export raw data", detail: "Click Export to CSV when you need the numbers for a report or a spreadsheet." },
    ],
  },
  {
    id: "performance", icon: Activity, group: "Analytics", name: "Page Performance",
    short: "Per-page SEO score, load time and core web vitals.",
    steps: ["Select a page.", "Read the score breakdown and improvement tips.", "Run an AI fix in one click."],
  },
  {
    id: "content-calendar", icon: CalendarDays, group: "Analytics", name: "Content Calendar",
    short: "Schedule and plan future publishes.",
    steps: ["Pick a date.", "Drag a page or campaign onto the date.", "It auto-publishes at the scheduled time."],
  },
  {
    id: "seo-audit", icon: ClipboardCheck, group: "Analytics", name: "SEO Audit",
    short: "Site-wide SEO health check — duplicate content, missing meta, broken links.",
    steps: ["Pick a site.", "Click 'Run Audit'.", "Fix issues in priority order."],
  },
  {
    id: "indexing", icon: Search, group: "Analytics", name: "Google Indexing",
    short: "Submit generated pages directly to Google.",
    steps: ["Connect Google Search Console.", "Select pages and click 'Submit for indexing'."],
  },
  {
    id: "affiliate", icon: Gift, group: "Account", name: "Affiliate",
    short: "Share your referral link and earn commission.",
    steps: ["Copy your unique link.", "Share it with friends or clients.", "Track earnings on the dashboard."],
  },
  {
    id: "referral", icon: Link2, group: "Account", name: "Referral",
    short: "Invite users with a tracked link and earn reward credits when they join.",
    steps: [
      "Copy your referral link from the Referral page.",
      "Share it — every signup and conversion is tracked automatically.",
      "Earned reward credits are applied to your account.",
    ],
    tips: ["Affiliate pays cash commission; Referral rewards you with in-app credits — you can use both."],
    guide: [
      { title: "Open Referral", detail: "Sidebar → Referral. Your unique tracked referral link is shown at the top." },
      { title: "Copy your link", detail: "Click Copy. The link carries your referral code so every visit is attributed to you." },
      { title: "Share it", detail: "Send the link to friends, clients or your audience — social, email or a blog all work." },
      { title: "Track signups", detail: "Each click, signup and conversion is recorded automatically and shown on the page." },
      { title: "Earn reward credits", detail: "When a referred user converts, reward credits are added to your account per the reward settings." },
      { title: "Spend the credits", detail: "Use the earned credits toward AI generations and other in-app usage." },
    ],
  },
  {
    id: "billing", icon: CreditCard, group: "Account", name: "Billing",
    short: "Plan upgrades, invoices and payment methods.",
    steps: ["Review your current plan.", "Upgrade or downgrade.", "Use the Stripe portal to download invoices."],
    guide: [
      { title: "Open Billing", detail: "Sidebar → Billing. Your current plan, usage limits and remaining AI credits are shown at the top." },
      { title: "Compare plans", detail: "Review Free, Starter, Pro and Agency. Each lists its template limit, page limit, AI credits and team features." },
      { title: "Choose a plan", detail: "Click Upgrade (or downgrade) on the plan that fits. Pro/Agency unlock unlimited templates and team collaboration." },
      { title: "Pay securely", detail: "Checkout is handled by Stripe. Enter your card details on the secure Stripe page — the app never stores your card." },
      { title: "Confirm activation", detail: "After payment you return to the app and the new limits apply immediately. A success message confirms the upgrade." },
      { title: "Manage payment & invoices", detail: "Use the Stripe customer portal to update your card, change the plan, or download past invoices." },
      { title: "Watch your usage", detail: "Track page and AI-credit usage on Billing so you upgrade before hitting a limit." },
    ],
  },
  {
    id: "settings", icon: Settings, group: "Account", name: "Settings",
    short: "Profile, language, theme and notifications.",
    steps: ["Update profile info.", "Switch language (29 supported).", "Set notification preferences."],
  },
  {
    id: "workspace-settings", icon: Users, group: "Account", name: "Workspace Settings",
    short: "Invite team members and manage roles (Pro/Agency only).",
    steps: ["Click 'Invite Member'.", "Set the email and role (admin/editor/viewer).", "Review every action in the audit log."],
  },
];

const GROUPS = ["Core", "PGP Suite", "Discovery", "Analytics", "Account"] as const;
const QUICK_FLOW = [
  { step: 1, title: "Connect a website", desc: "Sidebar → Websites → Add → WordPress (App Password) or Shopify (OAuth)." },
  { step: 2, title: "Pick or build a template", desc: "Templates → New (Manual / AI Generate / Scan / Import) or import from the Marketplace. Click 'AI Add Variables' to inject placeholders." },
  { step: 3, title: "Create a Keyword Group", desc: "Keywords → Keyword Groups → New. Choose the template, language, business/niche context and terms-per-variable." },
  { step: 4, title: "Generate a Campaign", desc: "From the Keyword Group click 'Generate campaign'. Add Locations + Business Info, pick Zip vs Cross, then Generate — pages publish straight to your site." },
];


interface Integration {
  name: string;
  connects: string;
  used: string;
  how: string;
}

const INTEGRATIONS: Integration[] = [
  {
    name: "WordPress",
    connects: "Websites · WP Control",
    used: "Publish generated pages, sync content, remote-manage the site",
    how: "Install the 3XVISIBILITY connector plugin, then add the site with an Application Password.",
  },
  {
    name: "WooCommerce",
    connects: "Websites · Campaigns",
    used: "Publish product & category landing pages on a WordPress store",
    how: "Connect the WordPress site first; WooCommerce is detected automatically.",
  },
  {
    name: "Shopify",
    connects: "Websites · Website Content",
    used: "Sync products, bulk SEO, publish pages to your store",
    how: "Use the one-click Shopify OAuth flow (Connect Shopify) — no manual keys needed.",
  },
  {
    name: "PrestaShop",
    connects: "Websites · Campaigns",
    used: "Publish pages and product content to a PrestaShop store",
    how: "Add the site URL and API key under Websites → Add.",
  },
  {
    name: "Google Search Console",
    connects: "Indexing · SEO Audit",
    used: "Submit generated pages to Google for faster indexing",
    how: "Connect a Google service account, then submit pages from the Indexing page.",
  },
  {
    name: "AI (Gemini)",
    connects: "AI Site Builder · Templates · Campaigns · Data CSV",
    used: "Generate designs, copy, images, keywords and fill missing data",
    how: "Built in — no API key required. Light tasks use the cheapest model to save credits.",
  },
  {
    name: "Stripe (Billing)",
    connects: "Billing",
    used: "Plan upgrades, invoices and payment methods",
    how: "Managed for you — upgrade from Billing and use the portal for invoices.",
  },
];

interface ConnectField {
  label: string;
  desc: string;
}

interface ConnectTutorial {
  id: string;
  name: string;
  icon: React.ElementType;
  intro: string;
  fields: ConnectField[];
  permissions: string[];
  test: string[];
  troubleshoot?: string[];
}

const CONNECT_TUTORIALS: ConnectTutorial[] = [
  {
    id: "connect-wordpress",
    name: "Connect WordPress (self-hosted)",
    icon: Globe,
    intro: "Publish and sync pages to your own WordPress site using a secure Application Password. Works with WordPress 5.6+ over HTTPS.",
    fields: [
      { label: "Site URL", desc: "Your full site address, e.g. https://yoursite.com — include https:// and the www prefix only if your site uses it." },
      { label: "Username", desc: "The WordPress admin/editor username the pages will be published as." },
      { label: "Application Password", desc: "A dedicated password (not your login password). Create it in WordPress: Users → Profile → Application Passwords → enter a name → Add New." },
      { label: "Connector plugin", desc: "Install & activate the 3XVISIBILITY WordPress connector plugin for best publishing fidelity (Elementor, critical CSS, media)." },
    ],
    permissions: [
      "The account must have Editor or Administrator role to create and update pages.",
      "Pretty permalinks must be enabled (Settings → Permalinks → anything except 'Plain') so the REST API works.",
      "The site must be served over HTTPS — Application Passwords are disabled on plain HTTP.",
    ],
    test: [
      "Go to Websites → + Add Website → choose WordPress.",
      "Fill in Site URL, Username and Application Password.",
      "Click 'Test Connection'.",
      "A green tick means it worked — click Save. Content from the site is then pulled in automatically.",
    ],
    troubleshoot: [
      "SSL / SNI error → check whether the URL needs (or must drop) the www prefix; if it persists, contact your host.",
      "'rest_no_route' error → enable pretty permalinks in WordPress.",
      "401 Unauthorized → regenerate the Application Password and make sure you copied it without spaces.",
    ],
  },
  {
    id: "connect-shopify",
    name: "Connect Shopify",
    icon: Store,
    intro: "Connect your Shopify store with a one-click OAuth flow — no manual API keys to copy. Once connected you can sync products, run bulk SEO and publish pages.",
    fields: [
      { label: "Store domain", desc: "Your myshopify domain, e.g. your-store.myshopify.com (used to start the OAuth handshake)." },
      { label: "Connect button", desc: "Click 'Connect Shopify' — you're redirected to Shopify to log in and approve access. No keys are entered by hand." },
    ],
    permissions: [
      "You must be the store owner or a staff account with app-install permission.",
      "On the Shopify approval screen, grant access to Products and Content so the app can read/write product and page data.",
      "Access is per-user and revocable at any time from Shopify → Settings → Apps and sales channels.",
    ],
    test: [
      "Go to Websites → + Add Website → choose Shopify (or open the Shopify guide page).",
      "Enter your .myshopify.com domain and click 'Connect Shopify'.",
      "Approve the requested permissions on Shopify's screen.",
      "You're returned to the app with a connected status — products appear under Website Content once synced.",
    ],
    troubleshoot: [
      "Redirect fails or 'app not found' → confirm the store domain is spelled correctly and ends in .myshopify.com.",
      "Permissions error later → reconnect and make sure Products & Content scopes are approved.",
    ],
  },
  {
    id: "connect-gsc",
    name: "Connect Google Search Console",
    icon: Search,
    intro: "Connect Google Search Console to submit generated pages to Google and monitor indexing. Uses a Google service account with access to your verified property.",
    fields: [
      { label: "Property (site URL)", desc: "The exact verified property from Search Console — either a Domain property (sc-domain:example.com) or a URL-prefix (https://example.com/). Pick it from the list; don't type a random URL." },
      { label: "Service account JSON", desc: "The credentials key file for a Google Cloud service account. Paste/upload it in Websites settings — it is stored securely and never shown in the browser." },
    ],
    permissions: [
      "The property must already be verified in Google Search Console.",
      "Add the service account email as a user on the property: Search Console → Settings → Users and permissions → Add user (Full or Owner).",
      "Enable the 'Google Search Console API' (and Indexing API for submissions) in the Google Cloud project.",
    ],
    test: [
      "Connect the Google service account under Websites / SEO settings.",
      "Open the Indexing page — your verified properties load in the selector.",
      "Select a property; if pages list without a 403, the connection works.",
      "Select pages and click 'Submit for indexing' to send them to Google.",
    ],
    troubleshoot: [
      "403 on a property → the service account isn't added as a user, or the property isn't verified.",
      "Empty property list → confirm the property exists and is verified in Search Console for that Google account.",
    ],
  },
];

interface WalkStep {
  title: string;
  detail: string;
  tip?: string;
}

const E2E_WALKTHROUGH: WalkStep[] = [
  {
    title: "Prepare & upload your CSV",
    detail:
      "Go to Data (CSV) → Upload CSV, or download a ready-made starter from any template's 'Download CSV' button. Each column becomes a variable (e.g. city, service, phone). The first row is the header; every following row generates one page.",
    tip: "Use the per-template starter CSV so the column names already match the template's variables.",
  },
  {
    title: "Create a template (or pick one)",
    detail:
      "Open Templates → New Template (or reuse a marketplace/AI-built one). Insert your variables as {{city}}, {{service}} etc. in the HTML, headings and meta fields. Preview to confirm the design and that variables resolve.",
    tip: "AI Site Builder can generate a full template for you — then just add the variables.",
  },
  {
    title: "Start a campaign",
    detail:
      "Go to Campaigns → New Campaign. Name it, choose the type (SEO / SEA / GEO) and select the template you just prepared.",
  },
  {
    title: "Attach the CSV & map columns",
    detail:
      "In the wizard's Data step, select your uploaded CSV. In the Mapping step, match each CSV column to the matching template variable. Unmapped variables fall back to defaults or AI suggestions.",
    tip: "Green ticks in the mapping step mean every required variable is filled.",
  },
  {
    title: "Set keyword source & publish mode",
    detail:
      "Choose where keywords/terms come from (CSV column, extracted, or AI-generated). Then set the publish target to WordPress and the website you connected earlier.",
  },
  {
    title: "Generate the pages",
    detail:
      "Click Generate. Watch the progress list — each row shows its status (queued → generating → success/failed) plus whether keywords/terms were regenerated. Failed rows can be retried individually.",
  },
  {
    title: "Publish to WordPress",
    detail:
      "With publish mode set to WordPress, generated pages are pushed straight to your connected site (Elementor/critical-CSS fidelity preserved). Or generate first, review, then click Publish per page or in bulk.",
    tip: "Make sure your WordPress connection shows a green status in Websites before publishing.",
  },
  {
    title: "Verify & index",
    detail:
      "Open a published URL on your WordPress site to confirm layout and variables look right. Then use the Indexing page (Google Search Console) to submit the new pages to Google.",
  },
];

interface FaqItem {
  q: string;
  a: string;
}

const FAQS: FaqItem[] = [
  {
    q: "Why does my website connection keep failing?",
    a: "The most common causes are: wrong URL format (missing https:// or extra www), invalid Application Password, pretty permalinks disabled on WordPress, or an SSL/SNI mismatch. Use the 'Test Connection' button after fixing each one.",
  },
  {
    q: "I uploaded a CSV but variables are not mapping — what's wrong?",
    a: "Make sure the first row contains column headers and that the column names exactly match the template variables (lowercase_snake_case). Empty columns or extra spaces in headers break auto-mapping.",
  },
  {
    q: "Pages show 'Generated' but are not live on my site — why?",
    a: "Check the publish mode in the campaign (Draft vs Live). Draft pages are not pushed to the CMS. Also confirm the website connection still shows a green status in Websites.",
  },
  {
    q: "Why do I see a 401 / 403 error when publishing?",
    a: "401 means the credentials are rejected (regenerate the Application Password or reconnect OAuth). 403 means the connected account lacks permission to create/update pages — use an Editor or Administrator account.",
  },
  {
    q: "My generated pages look different from the preview — how do I fix it?",
    a: "Make sure the 3XVISIBILITY WordPress connector plugin is installed and active. It preserves Elementor layout, container widths and critical CSS. Without it, styling may fall back to default theme styles.",
  },
  {
    q: "Can I undo a bulk delete or republish?",
    a: "Bulk delete is permanent — there is no undo. Republish is safe because it only updates existing pages. Always read confirmation dialogs before confirming destructive actions.",
  },
  {
    q: "How are AI credits kept low?",
    a: "Light tasks always use Gemini Flash Lite (the cheapest model). Images fall back to Unsplash and translations to LibreTranslate whenever possible.",
  },
  {
    q: "If a marketplace template is updated, do my pages change?",
    a: "No. Version pinning saves your copy as a snapshot — marketplace updates do not affect it.",
  },
  {
    q: "Where do I upgrade my plan?",
    a: "Sidebar → Billing → Upgrade plan. Pro/Agency unlock more templates, credits and team features.",
  },
];

interface TroubleshootItem {
  category: string;
  icon: React.ElementType;
  problems: { symptom: string; fix: string }[];
}

const TROUBLESHOOTING: TroubleshootItem[] = [
  {
    category: "Connection failures",
    icon: Plug,
    problems: [
      {
        symptom: "Test Connection shows a red cross or timeout",
        fix: "Check the URL starts with https:// and matches exactly what the site serves (with or without www). Try opening the URL in a browser first.",
      },
      {
        symptom: "WordPress: 'rest_no_route' or 404 on test",
        fix: "Enable pretty permalinks in WordPress: Settings → Permalinks → choose any option except 'Plain' → Save Changes.",
      },
      {
        symptom: "Shopify OAuth redirect fails",
        fix: "Confirm the store domain ends in .myshopify.com and is spelled exactly as shown in your Shopify admin.",
      },
      {
        symptom: "Google Search Console property list is empty",
        fix: "The service account must have access to a verified property. Add the service-account email in Search Console → Settings → Users and permissions.",
      },
    ],
  },
  {
    category: "Authorization problems",
    icon: KeyRound,
    problems: [
      {
        symptom: "401 Unauthorized when testing WordPress",
        fix: "Regenerate the Application Password in WordPress (Users → Profile → Application Passwords). Copy the full password without spaces and paste it again.",
      },
      {
        symptom: "403 Forbidden when publishing pages",
        fix: "The connected WordPress user must be Editor or Administrator. Viewer/Author/Contributor accounts cannot create pages through the REST API.",
      },
      {
        symptom: "Shopify shows 'insufficient permissions' after OAuth",
        fix: "Reconnect and approve Products and Content scopes on the Shopify approval screen. Only store owners or staff with app-install permission can do this.",
      },
      {
        symptom: "Google Search Console returns 403 on submission",
        fix: "Add the service account email as a Full user or Owner on the exact property. Domain-level properties need the service account added at the domain level.",
      },
    ],
  },
  {
    category: "CSV parsing errors",
    icon: Database,
    problems: [
      {
        symptom: "Upload fails with 'Invalid CSV format'",
        fix: "Save the file as UTF-8 CSV with commas or semicolons. Make sure there are no merged cells and that every row has the same number of columns as the header.",
      },
      {
        symptom: "Special characters or accents look broken",
        fix: "Re-save the CSV as UTF-8 (in Excel / Google Sheets use File → Download → CSV UTF-8). Then re-upload.",
      },
      {
        symptom: "Variables stay unmapped after upload",
        fix: "Header names must match template variables exactly: lowercase, underscores instead of spaces, e.g. service_name not Service Name. Trim leading/trailing spaces.",
      },
      {
        symptom: "Spintax variations are not spinning",
        fix: "Separate variations with a pipe (|) inside the same cell, e.g. 'Roofing|Siding|Gutters'. Do not use commas or new lines for variations.",
      },
    ],
  },
  {
    category: "Publishing failures",
    icon: Globe,
    problems: [
      {
        symptom: "Campaign shows 'Published' but pages are missing on the site",
        fix: "Check publish mode was set to Live, not Draft. Draft pages are saved inside the app and not pushed to the CMS.",
      },
      {
        symptom: "Published page layout is broken or styles missing",
        fix: "Install and activate the 3XVISIBILITY WordPress connector plugin. It sends Elementor/container settings and critical-CSS fallback needed for fidelity.",
      },
      {
        symptom: "Some rows failed while others succeeded",
        fix: "Open the failed row's log. Common causes: a missing required variable, a special character in the title, or the CMS rejecting duplicate slugs.",
      },
      {
        symptom: "Images are missing after publish",
        fix: "Make sure the WordPress media library is writable and the connector plugin is active. Large images may also be blocked by server upload limits.",
      },
    ],
  },
];

const esc = (s: string) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** Build a self-contained, printable HTML guide from the documentation content
 *  and open it in a new window ready to "Save as PDF". No external deps. */
const GUIDE_SECTIONS = [
  { id: "sec-getting-started", title: "Getting started — 4 quick steps", label: "Getting started" },
  { id: "sec-tools", title: "Tools & features", label: "Tool guides" },
  { id: "sec-connect", title: "Connection tutorials", label: "Connection tutorials" },
  { id: "sec-example", title: "Full end-to-end example", label: "Full example" },
  { id: "sec-faq", title: "Frequently asked questions", label: "FAQ" },
  { id: "sec-troubleshoot", title: "Troubleshooting", label: "Troubleshooting" },
] as const;

type PresetId = "all" | "essentials" | "connections" | "custom";

interface GuidePreset {
  id: PresetId;
  label: string;
  sections: string[];
}

const GUIDE_PRESETS: GuidePreset[] = [
  {
    id: "all",
    label: "All sections",
    sections: GUIDE_SECTIONS.map((s) => s.id),
  },
  {
    id: "essentials",
    label: "Essentials",
    sections: ["sec-getting-started", "sec-example", "sec-faq"],
  },
  {
    id: "connections",
    label: "Connection help",
    sections: ["sec-connect", "sec-troubleshoot", "sec-faq"],
  },
  {
    id: "custom",
    label: "Custom",
    sections: [],
  },
];

interface ExportHistoryEntry {
  id: string;
  ts: number;
  sectionIds: string[];
  preset: PresetId;
}

const EXPORT_HISTORY_KEY = "docs-pdf-export-history";

function loadExportHistory(): ExportHistoryEntry[] {
  try {
    const raw = localStorage.getItem(EXPORT_HISTORY_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

const sectionLabel = (id: string) =>
  GUIDE_SECTIONS.find((s) => s.id === id)?.label ?? id;



/** Static UI strings embedded in the printable guide (translated like the rest). */
const GUIDE_STATIC_STRINGS = [
  "3XVISIBILITY — Quickstart Guide",
  "Complete step-by-step guide to every tool. Generated",
  "Table of contents",
  "Tips:",
  "Fields:",
  "Permissions:",
  "Test steps:",
  "Troubleshooting:",
  "Tip:",
];

/** Every English string the guide renders, so we can translate them in one pass. */
function collectGuideStrings(): string[] {
  const out = new Set<string>(GUIDE_STATIC_STRINGS);
  GUIDE_SECTIONS.forEach((s) => out.add(s.title));
  TOOLS.forEach((t) => {
    out.add(t.group);
    out.add(t.name);
    out.add(t.short);
    t.steps.forEach((s) => out.add(s));
    t.tips?.forEach((s) => out.add(s));
  });
  CONNECT_TUTORIALS.forEach((t) => {
    out.add(t.name);
    out.add(t.intro);
    t.fields.forEach((f) => {
      out.add(f.label);
      out.add(f.desc);
    });
    t.permissions.forEach((s) => out.add(s));
    t.test.forEach((s) => out.add(s));
    t.troubleshoot?.forEach((s) => out.add(s));
  });
  E2E_WALKTHROUGH.forEach((s) => {
    out.add(s.title);
    out.add(s.detail);
    if (s.tip) out.add(s.tip);
  });
  FAQS.forEach((f) => {
    out.add(f.q);
    out.add(f.a);
  });
  TROUBLESHOOTING.forEach((c) => {
    out.add(c.category);
    c.problems.forEach((p) => {
      out.add(p.symptom);
      out.add(p.fix);
    });
  });
  QUICK_FLOW.forEach((s) => {
    out.add(s.title);
    out.add(s.desc);
  });
  return [...out];
}

const GUIDE_TR_CACHE_PREFIX = "docs-guide-tr:";

/**
 * Translate all guide strings into the target language via the translate-ui
 * edge function, in batches. Results are cached in localStorage so repeat
 * downloads are instant. Falls back to the English original on any failure.
 */
async function translateGuideStrings(target: string): Promise<(s: string) => string> {
  const identity = (s: string) => s;
  if (target === "en") return identity;

  const strings = collectGuideStrings();
  const cacheKey = `${GUIDE_TR_CACHE_PREFIX}${target}`;
  let map: Record<string, string> = {};
  try {
    const cached = localStorage.getItem(cacheKey);
    if (cached) {
      const parsed = JSON.parse(cached) as Record<string, string>;
      if (parsed && typeof parsed === "object" && strings.every((s) => typeof parsed[s] === "string")) {
        map = parsed;
      }
    }
  } catch {
    /* ignore cache errors */
  }

  const missing = strings.filter((s) => typeof map[s] !== "string");
  if (missing.length) {
    const BATCH = 20;
    for (let i = 0; i < missing.length; i += BATCH) {
      const slice = missing.slice(i, i + BATCH);
      try {
        const { data, error } = await supabase.functions.invoke("translate-ui", {
          body: { texts: slice, target },
        });
        const raw = (data as { translations?: unknown[] })?.translations;
        if (!error && Array.isArray(raw) && raw.length === slice.length) {
          slice.forEach((s, j) => {
            const v = raw[j];
            map[s] = typeof v === "string" && v.trim() ? v : s;
          });
        } else {
          slice.forEach((s) => {
            map[s] = s;
          });
        }
      } catch {
        slice.forEach((s) => {
          map[s] = s;
        });
      }
    }
    try {
      localStorage.setItem(cacheKey, JSON.stringify(map));
    } catch {
      /* storage full — fine, we still have the in-memory map */
    }
  }

  return (s: string) => map[s] ?? s;
}

function buildGuideHtml(selectedIds?: string[], forPrint = true, tr: (s: string) => string = (s) => s): string {
  const e = (s: string) => esc(tr(s));
  const li = (items: string[]) =>
    `<ul>${items.map((i) => `<li>${e(i)}</li>`).join("")}</ul>`;

  const toolsHtml = GROUPS.map((group) => {
    const tools = TOOLS.filter((t) => t.group === group);
    return `<h2>${esc(group)}</h2>${tools
      .map(
        (t) => `
        <div class="card">
          <h3>${esc(t.name)}</h3>
          <p class="muted">${esc(t.short)}</p>
          ${li(t.steps)}
          ${t.tips?.length ? `<p class="tip"><strong>Tips:</strong></p>${li(t.tips)}` : ""}
        </div>`
      )
      .join("")}`;
  }).join("");

  const connectHtml = CONNECT_TUTORIALS.map(
    (t) => `
    <div class="card">
      <h3>${esc(t.name)}</h3>
      <p class="muted">${esc(t.intro)}</p>
      <p><strong>Fields:</strong></p>
      <ul>${t.fields.map((f) => `<li><strong>${esc(f.label)}:</strong> ${esc(f.desc)}</li>`).join("")}</ul>
      <p><strong>Permissions:</strong></p>${li(t.permissions)}
      <p><strong>Test steps:</strong></p><ol>${t.test.map((s) => `<li>${esc(s)}</li>`).join("")}</ol>
      ${t.troubleshoot?.length ? `<p><strong>Troubleshooting:</strong></p>${li(t.troubleshoot)}` : ""}
    </div>`
  ).join("");

  const walkHtml = `<ol>${E2E_WALKTHROUGH.map(
    (s) =>
      `<li><strong>${esc(s.title)}</strong><br/>${esc(s.detail)}${
        s.tip ? `<br/><em>Tip: ${esc(s.tip)}</em>` : ""
      }</li>`
  ).join("")}</ol>`;

  const faqHtml = FAQS.map(
    (f) => `<div class="faq"><p><strong>Q: ${esc(f.q)}</strong></p><p>${esc(f.a)}</p></div>`
  ).join("");

  const troubleHtml = TROUBLESHOOTING.map(
    (c) => `
    <div class="card">
      <h3>${esc(c.category)}</h3>
      <ul>${c.problems
        .map((p) => `<li><strong>${esc(p.symptom)}</strong><br/>${esc(p.fix)}</li>`)
        .join("")}</ul>
    </div>`
  ).join("");

  const quickHtml = `<ol>${QUICK_FLOW.map(
    (s) => `<li><strong>${esc(s.title)}</strong> — ${esc(s.desc)}</li>`
  ).join("")}</ol>`;

  const allSections = [
    { id: "sec-getting-started", title: "Getting started — 4 quick steps", body: quickHtml },
    { id: "sec-tools", title: "Tools & features", body: toolsHtml },
    { id: "sec-connect", title: "Connection tutorials", body: connectHtml },
    { id: "sec-example", title: "Full end-to-end example", body: walkHtml },
    { id: "sec-faq", title: "Frequently asked questions", body: faqHtml },
    { id: "sec-troubleshoot", title: "Troubleshooting", body: troubleHtml },
  ];

  const sections =
    selectedIds && selectedIds.length
      ? (selectedIds
          .map((id) => allSections.find((s) => s.id === id))
          .filter(Boolean) as typeof allSections)
      : allSections;

  const tocHtml = `<nav class="toc">
    <h2 class="toc-title">Table of contents</h2>
    <ol>${sections
      .map(
        (s, i) =>
          `<li><a href="#${s.id}"><span class="toc-name">${esc(s.title)}</span><span class="toc-dots"></span><span class="toc-page">${i + 1}</span></a></li>`
      )
      .join("")}</ol>
  </nav>`;

  const sectionsHtml = sections
    .map(
      (s, i) =>
        `<section id="${s.id}" class="doc-section"><h2><span class="sec-num">${i + 1}.</span> ${esc(
          s.title
        )}</h2>${s.body}</section>`
    )
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8"/>
    <title>3XVISIBILITY — Quickstart Guide</title>
    <style>
      @page{size:A4;margin:18mm 16mm}
      *{box-sizing:border-box}
      html{-webkit-print-color-adjust:exact;print-color-adjust:exact}
      body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:#111;line-height:1.55;font-size:12pt;max-width:820px;margin:0 auto;padding:40px 32px}
      h1{font-size:26pt;margin:0 0 6px;letter-spacing:-0.01em}
      h2{font-size:16pt;margin:26px 0 10px;border-bottom:2px solid #eee;padding-bottom:4px;break-after:avoid;page-break-after:avoid}
      h3{font-size:12.5pt;margin:0 0 4px;break-after:avoid;page-break-after:avoid}
      p{margin:6px 0;orphans:3;widows:3}
      ul,ol{margin:6px 0 6px 20px;padding:0}
      li{margin:3px 0;break-inside:avoid;page-break-inside:avoid}
      a{text-decoration:none;color:#7c3aed}
      code,pre,.code{font-family:"SFMono-Regular",Consolas,"Liberation Mono",Menlo,monospace;font-size:10.5pt}
      code{background:#f4f4f6;color:#b4227a;padding:1px 5px;border-radius:4px}
      pre{background:#1e1e2e;color:#e6e6f0;padding:12px 14px;border-radius:8px;overflow-x:auto;white-space:pre-wrap;word-break:break-word;margin:8px 0;break-inside:avoid;page-break-inside:avoid;border:1px solid #2a2a3c}
      pre code{background:transparent;color:inherit;padding:0}
      .muted{color:#555}
      .tip{color:#a15c00;margin-top:8px}
      .card{border:1px solid #e5e5e5;border-radius:8px;padding:12px 16px;margin:10px 0;break-inside:avoid;page-break-inside:avoid}
      .faq{margin:8px 0;break-inside:avoid;page-break-inside:avoid}
      .cover{text-align:center;margin-bottom:24px}
      .cover p{color:#555}
      .sec-num{color:#7c3aed}
      .toc{margin:24px 0 12px;break-after:page;page-break-after:always}
      .toc-title{border-bottom:2px solid #eee;padding-bottom:4px}
      .toc ol{list-style:none;margin:12px 0 0;padding:0;counter-reset:toc}
      .toc li{margin:8px 0}
      .toc a{display:flex;align-items:baseline;text-decoration:none;color:#111;font-size:12pt}
      .toc-name{white-space:nowrap}
      .toc-dots{flex:1;border-bottom:1px dotted #bbb;margin:0 6px;transform:translateY(-3px)}
      .toc-page{color:#7c3aed;font-weight:600}
      .doc-section{break-before:page;page-break-before:always}
      .doc-section:first-of-type{break-before:avoid;page-break-before:avoid}
      @media print{body{padding:0}a{color:#111}}
    </style></head>
    <body>
      <div class="cover">
        <h1>3XVISIBILITY — Quickstart Guide</h1>
        <p>Complete step-by-step guide to every tool. Generated ${new Date().toLocaleDateString()}</p>
      </div>
      ${tocHtml}
      ${sectionsHtml}
      ${forPrint ? '<script>window.onload=function(){setTimeout(function(){window.print();},400);};</script>' : ''}
    </body></html>`;

  return html;
}

function buildAndDownloadGuide(selectedIds?: string[]) {
  const html = buildGuideHtml(selectedIds, true);
  const w = window.open("", "_blank");
  if (!w) {
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "3XVISIBILITY-Quickstart-Guide.html";
    a.click();
    URL.revokeObjectURL(url);
    return "download";
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
  return "print";
}

export default function DocumentationPage() {
  const [active, setActive] = useState<string>("getting-started");
  const [generating, setGenerating] = useState(false);
  const [selectedSections, setSelectedSections] = useState<string[]>(
    GUIDE_SECTIONS.map((s) => s.id)
  );
  // Ordered list of all section ids — drives both the picker order and export order.
  const [sectionOrder, setSectionOrder] = useState<string[]>(
    GUIDE_SECTIONS.map((s) => s.id)
  );
  const [activePreset, setActivePreset] = useState<PresetId>("all");
  const [dragId, setDragId] = useState<string | null>(null);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [exportHistory, setExportHistory] = useState<ExportHistoryEntry[]>(
    () => loadExportHistory()
  );

  const recordExport = (sectionIds: string[], preset: PresetId) => {
    setExportHistory((prev) => {
      const entry: ExportHistoryEntry = {
        id: `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
        ts: Date.now(),
        sectionIds,
        preset,
      };
      const next = [entry, ...prev].slice(0, 8);
      try {
        localStorage.setItem(EXPORT_HISTORY_KEY, JSON.stringify(next));
      } catch {
        // ignore storage failures
      }
      return next;
    });
  };

  const clearExportHistory = () => {
    setExportHistory([]);
    try {
      localStorage.removeItem(EXPORT_HISTORY_KEY);
    } catch {
      // ignore
    }
  };
  const pageRef = useRef<HTMLDivElement>(null);
  usePageAutoTranslate(pageRef, [active]);

  const applyPreset = (presetId: PresetId) => {
    setActivePreset(presetId);
    const preset = GUIDE_PRESETS.find((p) => p.id === presetId);
    if (preset && preset.sections.length > 0) {
      setSelectedSections(preset.sections);
    }
  };

  const toggleSection = (id: string) => {
    setSelectedSections((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
    );
    setActivePreset("custom");
  };

  const handleReorder = (targetId: string) => {
    if (!dragId || dragId === targetId) return;
    setSectionOrder((prev) => {
      const next = [...prev];
      const from = next.indexOf(dragId);
      const to = next.indexOf(targetId);
      if (from === -1 || to === -1) return prev;
      next.splice(from, 1);
      next.splice(to, 0, dragId);
      return next;
    });
    setActivePreset("custom");
  };

  // Sections ordered for export: custom drag order, filtered to selected.
  const orderedSelectedIds = sectionOrder.filter((id) =>
    selectedSections.includes(id)
  );

  // Live preview HTML — rebuilt whenever the selection or order changes.
  const previewHtml = useMemo(
    () =>
      orderedSelectedIds.length
        ? buildGuideHtml(orderedSelectedIds, false)
        : "",
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [orderedSelectedIds.join("|")]
  );

  const handleDownloadGuide = async (
    idsOverride?: string[],
    presetOverride?: PresetId
  ) => {
    if (generating) return;
    const ids = idsOverride ?? orderedSelectedIds;
    if (!ids.length) {
      toast.error("Select at least one section to export.");
      return;
    }
    setGenerating(true);
    const toastId = toast.loading("Generating your guide…");
    try {
      // Yield a frame so the loading UI paints before the heavy work.
      await new Promise((r) => setTimeout(r, 50));
      const result = buildAndDownloadGuide(ids);
      recordExport(ids, presetOverride ?? activePreset);
      if (result === "download") {
        toast.success("Guide downloaded", {
          id: toastId,
          description: "Popup was blocked, so we saved an HTML file instead. Open it and print to PDF.",
        });
      } else {
        toast.success("Guide ready", {
          id: toastId,
          description: "Opened in a new tab — choose \"Save as PDF\" in the print dialog.",
        });
      }
    } catch (err) {
      console.error("Guide generation failed", err);
      toast.error("Could not generate the guide", {
        id: toastId,
        description: err instanceof Error ? err.message : "Please try again in a moment.",
      });
    } finally {
      setGenerating(false);
    }
  };

  const handleReExport = (entry: ExportHistoryEntry) => {
    // Restore the historical selection/order into the UI, then export.
    setSectionOrder((prev) => {
      const rest = prev.filter((id) => !entry.sectionIds.includes(id));
      return [...entry.sectionIds, ...rest];
    });
    setSelectedSections(entry.sectionIds);
    setActivePreset(entry.preset);
    handleDownloadGuide(entry.sectionIds, entry.preset);
  };

  useEffect(() => {
    document.title = "Documentation — 3XVISIBILITY";
    const m = document.querySelector('meta[name="description"]');
    if (m) m.setAttribute("content", "Complete guide to 3XVISIBILITY tools — learn how to use campaigns, templates, websites and AI features.");
  }, []);

  return (
    <div className="min-h-screen bg-background text-foreground" ref={pageRef}>
      <Seo
        title="Documentation"
        description="Step-by-step guides for every 3XVISIBILITY tool — from connecting websites and building templates to generating and publishing pages at scale."
        path="/docs"
      />
      <LandingNav />

      <main className="container mx-auto px-4 lg:px-8 pt-28 pb-16" data-auto-translate>
        {/* Hero */}
        <header className="max-w-3xl mx-auto text-center mb-12">
          <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">
            <BookOpen className="h-3 w-3 mr-1" /> Documentation
          </Badge>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">
            Complete guide to every tool
          </h1>
          <p className="text-base md:text-lg text-muted-foreground">
            Step-by-step instructions for every feature in your workspace.
          </p>
          <div className="mt-6 flex flex-wrap justify-center items-center gap-3">
            <Button onClick={() => handleDownloadGuide()} size="lg" className="gap-2" disabled={generating}>
              {generating ? (
                <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</>
              ) : (
                <><FileText className="h-4 w-4" /> Download Quickstart Guide (PDF)</>
              )}
            </Button>
            <Button
              onClick={() => {
                if (!selectedSections.length) {
                  toast.error("Select at least one section to preview.");
                  return;
                }
                setPreviewOpen(true);
              }}
              variant="outline"
              size="lg"
              className="gap-2"
              disabled={generating}
            >
              <Eye className="h-4 w-4" /> Preview
            </Button>
            <Popover>
              <PopoverTrigger asChild>
                <Button variant="outline" size="lg" className="gap-2" disabled={generating}>
                  <SlidersHorizontal className="h-4 w-4" />
                  Sections ({selectedSections.length}/{GUIDE_SECTIONS.length})
                </Button>
              </PopoverTrigger>
              <PopoverContent align="center" className="w-80 text-left">
                <div className="mb-3">
                  <p className="text-sm font-medium mb-2">Preset</p>
                  <div className="flex flex-wrap gap-2">
                    {GUIDE_PRESETS.map((preset) => {
                      const isActive = activePreset === preset.id;
                      return (
                        <button
                          key={preset.id}
                          type="button"
                          onClick={() => applyPreset(preset.id)}
                          className={`px-2.5 py-1 rounded-full text-xs font-medium border transition-colors ${
                            isActive
                              ? "bg-primary text-primary-foreground border-primary"
                              : "bg-background text-muted-foreground border-border hover:border-primary/50 hover:text-foreground"
                          }`}
                        >
                          {preset.label}
                        </button>
                      );
                    })}
                  </div>
                </div>
                <div className="border-t border-border my-3" />
                <div className="mb-3 flex items-center justify-between">
                  <p className="text-sm font-medium">Sections to export</p>
                  <button
                    type="button"
                    className="text-xs text-primary hover:underline"
                    onClick={() => {
                      const selectingAll = selectedSections.length !== GUIDE_SECTIONS.length;
                      setSelectedSections(selectingAll ? GUIDE_SECTIONS.map((s) => s.id) : []);
                      setActivePreset(selectingAll ? "all" : "custom");
                    }}
                  >
                    {selectedSections.length === GUIDE_SECTIONS.length ? "Clear all" : "Select all"}
                  </button>
                </div>
                <p className="text-xs text-muted-foreground mb-2">
                  Drag the handle to reorder how sections appear in the PDF.
                </p>
                <div className="space-y-1.5">
                  {sectionOrder.map((id) => {
                    const s = GUIDE_SECTIONS.find((x) => x.id === id);
                    if (!s) return null;
                    const selected = selectedSections.includes(s.id);
                    return (
                      <div
                        key={s.id}
                        draggable
                        onDragStart={() => setDragId(s.id)}
                        onDragEnd={() => setDragId(null)}
                        onDragOver={(e) => {
                          e.preventDefault();
                          handleReorder(s.id);
                        }}
                        className={`flex items-center gap-2 rounded-md border px-2 py-1.5 transition-colors ${
                          dragId === s.id
                            ? "border-primary bg-primary/5"
                            : "border-transparent hover:border-border hover:bg-muted/40"
                        }`}
                      >
                        <button
                          type="button"
                          className="cursor-grab active:cursor-grabbing text-muted-foreground hover:text-foreground"
                          aria-label={`Reorder ${s.label}`}
                        >
                          <GripVertical className="h-4 w-4" />
                        </button>
                        <Checkbox
                          id={`export-${s.id}`}
                          checked={selected}
                          onCheckedChange={() => toggleSection(s.id)}
                        />
                        <Label
                          htmlFor={`export-${s.id}`}
                          className={`text-sm font-normal cursor-pointer flex-1 ${
                            selected ? "" : "text-muted-foreground"
                          }`}
                        >
                          {s.label}
                        </Label>
                      </div>
                    );
                  })}
                </div>

              </PopoverContent>
            </Popover>
          </div>
          <p className="mt-2 text-xs text-muted-foreground">
            Opens a printable version — choose "Save as PDF" in the print dialog.
          </p>






          {exportHistory.length > 0 && (
            <div className="mt-6 mx-auto max-w-xl text-left rounded-xl border border-border bg-card/50 p-4">
              <div className="flex items-center justify-between mb-3">
                <p className="text-sm font-medium flex items-center gap-2">
                  <HistoryIcon className="h-4 w-4 text-primary" /> Recent exports
                </p>
                <button
                  type="button"
                  className="text-xs text-muted-foreground hover:text-foreground hover:underline"
                  onClick={clearExportHistory}
                >
                  Clear
                </button>
              </div>
              <ul className="space-y-2">
                {exportHistory.map((entry) => (
                  <li
                    key={entry.id}
                    className="flex items-center justify-between gap-3 rounded-lg border border-border/60 bg-background px-3 py-2"
                  >
                    <div className="min-w-0">
                      <p className="text-xs text-muted-foreground">
                        {new Date(entry.ts).toLocaleString()} ·{" "}
                        {entry.sectionIds.length} section
                        {entry.sectionIds.length !== 1 ? "s" : ""}
                      </p>
                      <p className="text-sm truncate">
                        {entry.sectionIds.map(sectionLabel).join(", ")}
                      </p>
                    </div>
                    <Button
                      size="sm"
                      variant="outline"
                      className="gap-1.5 shrink-0"
                      disabled={generating}
                      onClick={() => handleReExport(entry)}
                    >
                      <RotateCcw className="h-3.5 w-3.5" /> Re-export
                    </Button>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </header>


        {/* Live PDF preview */}
        <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
          <DialogContent className="max-w-4xl w-[95vw] max-h-[92vh] flex flex-col">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Eye className="h-4 w-4" /> PDF preview
              </DialogTitle>
              <DialogDescription>
                Live preview of the guide with your selected sections and order
                ({orderedSelectedIds.length}/{GUIDE_SECTIONS.length} sections). This
                is how the pages will be laid out.
              </DialogDescription>
            </DialogHeader>
            <div className="flex-1 min-h-0 overflow-hidden rounded-lg border border-border bg-muted/30">
              {previewHtml ? (
                <iframe
                  title="PDF preview"
                  srcDoc={previewHtml}
                  className="w-full h-[70vh] bg-white"
                />
              ) : (
                <div className="flex items-center justify-center h-[70vh] text-sm text-muted-foreground">
                  Select at least one section to preview.
                </div>
              )}
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setPreviewOpen(false)}>
                Close
              </Button>
              <Button
                onClick={() => {
                  setPreviewOpen(false);
                  handleDownloadGuide();
                }}
                disabled={generating || !orderedSelectedIds.length}
                className="gap-2"
              >
                <FileText className="h-4 w-4" /> Download PDF
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>



        <div className="grid lg:grid-cols-[240px_1fr] gap-8">
          {/* Sidebar TOC */}
          <aside className="lg:sticky lg:top-24 lg:self-start">
            <nav className="space-y-1 text-sm">
              <a href="#getting-started" onClick={() => setActive("getting-started")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "getting-started" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                🚀 Getting Started
              </a>
              {GROUPS.map((g) => (
                <a key={g} href={`#group-${g.replace(/\s+/g, "-").toLowerCase()}`}
                  onClick={() => setActive(g)}
                  className={`block px-3 py-2 rounded-md transition-colors ${active === g ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                  {g}
                </a>
              ))}
              <a href="#integrations" onClick={() => setActive("integrations")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "integrations" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                🔌 Integrations
              </a>
              <a href="#connect-tutorials" onClick={() => setActive("connect-tutorials")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "connect-tutorials" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                🔗 Connection Tutorials
              </a>
              <a href="#full-example" onClick={() => setActive("full-example")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "full-example" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                🎯 Full Example
              </a>
              <a href="#faq" onClick={() => setActive("faq")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "faq" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                ❓ FAQ
              </a>
              <a href="#troubleshooting" onClick={() => setActive("troubleshooting")}
                className={`block px-3 py-2 rounded-md transition-colors ${active === "troubleshooting" ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}>
                🛠️ Troubleshooting
              </a>
            </nav>
          </aside>

          {/* Content */}
          <div className="space-y-12 min-w-0">
            {/* Getting Started */}
            <section id="getting-started" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <Rocket className="h-6 w-6 text-primary" /> Getting Started — 4 quick steps
              </h2>
              <p className="text-muted-foreground mb-6">
                New here? Follow this sequence and your first batch of pages will be live in about 10 minutes.
              </p>



              <ol className="space-y-3">
                {QUICK_FLOW.map((s) => (
                  <li key={s.step} className="flex gap-4 p-4 rounded-lg border border-border bg-card">
                    <div className="flex-shrink-0 h-8 w-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-sm">
                      {s.step}
                    </div>
                    <div>
                      <div className="font-semibold">{s.title}</div>
                      <div className="text-sm text-muted-foreground mt-0.5">{s.desc}</div>
                    </div>
                  </li>
                ))}
              </ol>
            </section>

            {/* Tool groups */}
            {GROUPS.map((group) => (
              <section key={group} id={`group-${group.replace(/\s+/g, "-").toLowerCase()}`} className="scroll-mt-24">
                <h2 className="text-2xl font-bold mb-6 border-b border-border pb-2">{group}</h2>
                <div className="space-y-6">
                  {TOOLS.filter((t) => t.group === group).map((tool) => {
                    const Icon = tool.icon;
                    return (
                      <article key={tool.id} id={tool.id} className="scroll-mt-24 rounded-xl border border-border bg-card p-5 md:p-6">
                        <header className="flex items-start gap-3 mb-3">
                          <div className="h-10 w-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center flex-shrink-0">
                            <Icon className="h-5 w-5" />
                          </div>
                          <div className="min-w-0">
                            <h3 className="font-semibold text-lg">{tool.name}</h3>
                            <p className="text-sm text-muted-foreground mt-0.5">{tool.short}</p>
                          </div>
                        </header>

                        <div className="ml-0 md:ml-13">
                          <h4 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-2 mt-4">
                            How to use it
                          </h4>
                          <ol className="space-y-1.5">
                            {tool.steps.map((s, i) => (
                              <li key={i} className="flex gap-2 text-sm">
                                <CheckCircle2 className="h-4 w-4 text-primary flex-shrink-0 mt-0.5" />
                                <span>{s}</span>
                              </li>
                            ))}
                          </ol>






                          {tool.guide && tool.guide.length > 0 && (
                            <details className="mt-4 rounded-md border border-primary/20 bg-primary/5 p-3 group/guide" open>
                              <summary className="flex items-center gap-1.5 text-xs font-semibold text-primary mb-1 cursor-pointer list-none">
                                <BookOpen className="h-3.5 w-3.5" /> Detailed step-by-step guide
                              </summary>
                              <ol className="mt-3 space-y-3">
                                {tool.guide.map((g, i) => (
                                  <li key={i} className="flex gap-3">
                                    <div className="flex-shrink-0 h-6 w-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-xs">
                                      {i + 1}
                                    </div>
                                    <div className="min-w-0">
                                      <div className="text-sm font-semibold">{g.title}</div>
                                      <div className="text-sm text-muted-foreground mt-0.5">{g.detail}</div>
                                    </div>
                                  </li>
                                ))}
                              </ol>
                            </details>
                          )}



                          {tool.tips && tool.tips.length > 0 && (
                            <div className="mt-4 rounded-md bg-amber-500/5 border border-amber-500/20 p-3">
                              <div className="flex items-center gap-1.5 text-xs font-semibold text-amber-600 dark:text-amber-400 mb-1">
                                <Lightbulb className="h-3.5 w-3.5" /> Tips
                              </div>
                              <ul className="space-y-1 text-xs text-muted-foreground">
                                {tool.tips.map((tip, i) => <li key={i}>• {tip}</li>)}
                              </ul>
                            </div>
                          )}
                        </div>
                      </article>
                    );
                  })}
                </div>
              </section>
            ))}

            {/* Integrations */}
            <section id="integrations" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <Plug className="h-6 w-6 text-primary" /> Integrations &amp; Connections
              </h2>
              <p className="text-muted-foreground mb-6">
                What connects with what — and how each connection is used across the app.
              </p>
              <div className="space-y-4">
                {INTEGRATIONS.map((it) => (
                  <div key={it.name} className="rounded-xl border border-border bg-card p-5">
                    <div className="flex flex-wrap items-center gap-2 mb-2">
                      <h3 className="font-semibold text-lg">{it.name}</h3>
                      <Badge variant="secondary" className="text-xs">{it.connects}</Badge>
                    </div>
                    <p className="text-sm mb-1"><span className="font-medium">Used for: </span><span className="text-muted-foreground">{it.used}</span></p>
                    <p className="text-sm"><span className="font-medium">How to connect: </span><span className="text-muted-foreground">{it.how}</span></p>
                  </div>
                ))}
              </div>
            </section>

            {/* Connection tutorials */}
            <section id="connect-tutorials" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <Plug className="h-6 w-6 text-primary" /> Connection tutorials
              </h2>
              <p className="text-muted-foreground mb-6">
                Full walkthroughs for connecting WordPress, Shopify and Google Search Console — input fields, permissions and how to test the connection.
              </p>
              <div className="space-y-6">
                {CONNECT_TUTORIALS.map((t) => {
                  const Icon = t.icon;
                  return (
                    <article key={t.id} id={t.id} className="scroll-mt-24 rounded-xl border border-border bg-card p-5 md:p-6">
                      <header className="flex items-start gap-3 mb-3">
                        <div className="h-10 w-10 rounded-lg bg-primary/10 text-primary flex items-center justify-center flex-shrink-0">
                          <Icon className="h-5 w-5" />
                        </div>
                        <div className="min-w-0">
                          <h3 className="font-semibold text-lg">{t.name}</h3>
                          <p className="text-sm text-muted-foreground mt-0.5">{t.intro}</p>
                        </div>
                      </header>

                      <div className="space-y-4 mt-4">
                        {/* Input fields */}
                        <div>
                          <h4 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-2">
                            Input fields
                          </h4>
                          <ul className="space-y-2">
                            {t.fields.map((f, i) => (
                              <li key={i} className="text-sm">
                                <span className="font-semibold">{f.label}</span>
                                <span className="text-muted-foreground"> — {f.desc}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        {/* Permissions */}
                        <div>
                          <h4 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-2">
                            Permissions required
                          </h4>
                          <ul className="space-y-1.5">
                            {t.permissions.map((p, i) => (
                              <li key={i} className="flex gap-2 text-sm">
                                <CheckCircle2 className="h-4 w-4 text-primary flex-shrink-0 mt-0.5" />
                                <span>{p}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        {/* Test connection */}
                        <div>
                          <h4 className="text-xs uppercase tracking-wider text-muted-foreground font-semibold mb-2">
                            Test the connection
                          </h4>
                          <ol className="space-y-3">
                            {t.test.map((s, i) => (
                              <li key={i} className="flex gap-3">
                                <div className="flex-shrink-0 h-6 w-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-xs">
                                  {i + 1}
                                </div>
                                <span className="text-sm mt-0.5">{s}</span>
                              </li>
                            ))}
                          </ol>
                        </div>

                        {/* Troubleshooting */}
                        {t.troubleshoot && t.troubleshoot.length > 0 && (
                          <div className="rounded-md bg-amber-500/5 border border-amber-500/20 p-3">
                            <div className="flex items-center gap-1.5 text-xs font-semibold text-amber-600 dark:text-amber-400 mb-1">
                              <AlertCircle className="h-3.5 w-3.5" /> Troubleshooting
                            </div>
                            <ul className="space-y-1 text-xs text-muted-foreground">
                              {t.troubleshoot.map((tip, i) => <li key={i}>• {tip}</li>)}
                            </ul>
                          </div>
                        )}
                      </div>
                    </article>
                  );
                })}
              </div>
            </section>

            {/* Full end-to-end example */}
            <section id="full-example" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <Rocket className="h-6 w-6 text-primary" /> Full example — CSV → Template → Campaign → WordPress
              </h2>
              <p className="text-muted-foreground mb-6">
                A complete end-to-end walkthrough: upload a CSV, pick a template, generate a campaign, and publish the pages straight to your WordPress site.
              </p>

              <div className="rounded-xl border border-primary/20 bg-gradient-to-br from-primary/5 to-transparent p-4 md:p-5 mb-6 text-sm">
                <span className="font-semibold text-primary">Before you start:</span>{" "}
                Connect your WordPress site (see the Connection Tutorials above) and make sure it shows a green status in Websites.
              </div>

              <ol className="space-y-4">
                {E2E_WALKTHROUGH.map((s, i) => (
                  <li key={i} className="rounded-xl border border-border bg-card p-4 md:p-5 flex gap-4">
                    <div className="flex-shrink-0 h-8 w-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-sm">
                      {i + 1}
                    </div>
                    <div className="min-w-0">
                      <h3 className="font-semibold">{s.title}</h3>
                      <p className="text-sm text-muted-foreground mt-1">{s.detail}</p>
                      {s.tip && (
                        <div className="mt-2 flex items-start gap-1.5 text-xs text-primary">
                          <Lightbulb className="h-3.5 w-3.5 flex-shrink-0 mt-0.5" />
                          <span>{s.tip}</span>
                        </div>
                      )}
                    </div>
                  </li>
                ))}
              </ol>

              <div className="mt-6 rounded-md bg-emerald-500/5 border border-emerald-500/20 p-4 text-sm">
                <div className="flex items-center gap-1.5 font-semibold text-emerald-600 dark:text-emerald-400 mb-1">
                  <CheckCircle2 className="h-4 w-4" /> Result
                </div>
                <p className="text-muted-foreground">
                  You now have a batch of unique, variable-driven pages live on your WordPress site — one per CSV row — ready to be indexed by Google.
                </p>
              </div>
            </section>


            {/* FAQ */}
            <section id="faq" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <HelpCircle className="h-6 w-6 text-primary" /> Frequently asked questions
              </h2>
              <p className="text-muted-foreground mb-6">
                Quick answers to the most common questions about connections, CSVs, publishing and account limits.
              </p>
              <div className="space-y-3">
                {FAQS.map((f, i) => (
                  <details key={i} className="rounded-lg border border-border bg-card p-4 group">
                    <summary className="font-medium cursor-pointer list-none flex items-center justify-between">
                      <span>{f.q}</span>
                      <ArrowRight className="h-4 w-4 text-muted-foreground group-open:rotate-90 transition-transform" />
                    </summary>
                    <p className="mt-3 text-sm text-muted-foreground">{f.a}</p>
                  </details>
                ))}
              </div>
            </section>

            {/* Troubleshooting */}
            <section id="troubleshooting" className="scroll-mt-24">
              <h2 className="text-2xl font-bold mb-2 flex items-center gap-2">
                <AlertCircle className="h-6 w-6 text-primary" /> Troubleshooting
              </h2>
              <p className="text-muted-foreground mb-6">
                Symptom-based fixes for connection, authorization, CSV and publishing problems.
              </p>
              <div className="space-y-6">
                {TROUBLESHOOTING.map((cat) => {
                  const Icon = cat.icon;
                  return (
                    <article key={cat.category} className="rounded-xl border border-border bg-card p-5 md:p-6">
                      <header className="flex items-center gap-2 mb-4">
                        <div className="h-9 w-9 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
                          <Icon className="h-5 w-5" />
                        </div>
                        <h3 className="font-semibold text-lg">{cat.category}</h3>
                      </header>
                      <div className="space-y-3">
                        {cat.problems.map((p, i) => (
                          <div key={i} className="rounded-md border border-border p-3">
                            <div className="flex items-start gap-2">
                              <span className="text-xs font-bold text-primary mt-0.5">SYMPTOM</span>
                              <p className="text-sm font-medium">{p.symptom}</p>
                            </div>
                            <div className="flex items-start gap-2 mt-2">
                              <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400 mt-0.5">FIX</span>
                              <p className="text-sm text-muted-foreground">{p.fix}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </article>
                  );
                })}
              </div>
            </section>

            {/* CTA */}
            <section className="rounded-xl border border-primary/20 bg-gradient-to-br from-primary/10 to-transparent p-6 md:p-8 text-center">
              <h2 className="text-xl font-bold mb-2">Still have questions?</h2>
              <p className="text-sm text-muted-foreground mb-4">Open the app and try it directly — every page has contextual help built in.</p>
              <Button asChild>
                <Link to="/dashboard">Go to the app <ArrowRight className="ml-2 h-4 w-4" /></Link>
              </Button>
            </section>
          </div>
        </div>
      </main>

      <LandingFooter />
    </div>
  );
}
