#!/usr/bin/env bun
/**
 * generate-locales.ts
 *
 * Reads the canonical JSON translation files from src/i18n/locales-json/
 * and generates:
 *   1. src/i18n/locales/*.ts  — individual typed locale files
 *   2. src/i18n/translations.ts — the combined translations export
 *
 * Usage:  bun scripts/generate-locales.ts
 *
 * The JSON files are the SINGLE SOURCE OF TRUTH. Never edit the generated
 * .ts files by hand — edit the JSON and re-run this script.
 */
import fs from "fs";
import path from "path";

const ROOT = path.resolve(import.meta.dir, "..");
const JSON_DIR = path.join(ROOT, "src/i18n/locales-json");
const TS_DIR = path.join(ROOT, "src/i18n/locales");
const TRANSLATIONS_PATH = path.join(ROOT, "src/i18n/translations.ts");

// ── Configuration ──────────────────────────────────────────────
// Primary languages shown in the language switcher
const PRIMARY_LANGUAGES: { code: string; label: string; flag: string }[] = [
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
  { code: "nl", label: "Nederlands", flag: "🇳🇱" },
  { code: "pl", label: "Polski", flag: "🇵🇱" },
];

const PRIMARY_CODES = PRIMARY_LANGUAGES.map((l) => l.code);

// ── Helpers ────────────────────────────────────────────────────
function readJson(filePath: string): Record<string, string> {
  return JSON.parse(fs.readFileSync(filePath, "utf-8"));
}

function toTsObjectLiteral(obj: Record<string, string>, indent = 2): string {
  const pad = " ".repeat(indent);
  const entries = Object.entries(obj)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => {
      const escaped = v.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      return `${pad}"${k}": "${escaped}",`;
    });
  return entries.join("\n");
}

// ── 1. Generate individual locale .ts files ────────────────────
fs.mkdirSync(TS_DIR, { recursive: true });

const jsonFiles = fs.readdirSync(JSON_DIR).filter((f) => f.endsWith(".json"));
const allCodes: string[] = [];

for (const file of jsonFiles) {
  const code = file.replace(".json", "");
  allCodes.push(code);
  const data = readJson(path.join(JSON_DIR, file));
  const body = toTsObjectLiteral(data);

  const ts = [
    `// Auto-generated from locales-json/${code}.json — DO NOT EDIT BY HAND`,
    `const ${code}: Record<string, string> = {`,
    body,
    `};`,
    ``,
    `export default ${code};`,
    ``,
  ].join("\n");

  fs.writeFileSync(path.join(TS_DIR, `${code}.ts`), ts);
}

console.log(`✓ Generated ${allCodes.length} locale .ts files`);

// ── 2. Generate translations.ts ────────────────────────────────
const imports = PRIMARY_CODES
  .map((c) => `import ${c}Locale from "./locales/${c}";`)
  .join("\n");

const languageType = PRIMARY_CODES.map((c) => `"${c}"`).join(" | ");

const languagesArray = PRIMARY_LANGUAGES.map(
  (l) => `  { code: "${l.code}", label: "${l.label}", flag: "${l.flag}" },`
).join("\n");

const translationsEntries = PRIMARY_CODES.map((c) => `  ${c}: ${c}Locale,`).join("\n");

const translationsTs = `// Auto-generated by scripts/generate-locales.ts — DO NOT EDIT BY HAND
// Edit the JSON files in src/i18n/locales-json/ and run: bun scripts/generate-locales.ts

${imports}

export type Language = ${languageType};

export const languages: { code: Language; label: string; flag: string }[] = [
${languagesArray}
];

export const translations: Record<Language, Record<string, string>> = {
${translationsEntries}
};
`;

fs.writeFileSync(TRANSLATIONS_PATH, translationsTs);
console.log(`✓ Generated translations.ts (${PRIMARY_CODES.length} languages)`);

// ── 3. Validate: check all primary locales have at least the same keys as en ──
const enKeys = new Set(Object.keys(readJson(path.join(JSON_DIR, "en.json"))));
let missingCount = 0;
for (const code of PRIMARY_CODES) {
  if (code === "en") continue;
  const filePath = path.join(JSON_DIR, `${code}.json`);
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠ Missing JSON for primary language: ${code}`);
    continue;
  }
  const keys = new Set(Object.keys(readJson(filePath)));
  const missing = [...enKeys].filter((k) => !keys.has(k));
  if (missing.length > 0) {
    console.warn(`⚠ ${code}: missing ${missing.length} keys vs en (first 5: ${missing.slice(0, 5).join(", ")})`);
    missingCount += missing.length;
  }
}

if (missingCount === 0) {
  console.log("✓ All primary languages have complete key coverage");
} else {
  console.warn(`⚠ ${missingCount} total missing keys across primary languages`);
}

console.log("\nDone!");
`;

fs.writeFileSync(TRANSLATIONS_PATH, translationsTs);
console.log(`✓ Generated translations.ts (${PRIMARY_CODES.length} languages)`);
