const ja: Record<string, string> = {
  "nav.features": "機能", "nav.howItWorks": "仕組み", "nav.pricing": "料金", "nav.faq": "FAQ", "nav.login": "ログイン", "nav.getStarted": "始める", "nav.lightMode": "ライトモード", "nav.darkMode": "ダークモード",
  "hero.badge": "AI搭載コンテンツ生成機能を搭載", "hero.title1": "データを", "hero.title2": "公開ページに変換", "hero.description": "プログラマティックSEO、SEA、GEOページのためのマルチテナントプラットフォーム。CSVをアップロードし、テンプレートにマッピングし、数百の最適化されたページを数分で生成・デプロイ。", "hero.cta": "無料で始める", "hero.watchDemo": "デモを見る", "hero.freeStart": "✓ 無料で開始", "hero.noCreditCard": "✓ クレジットカード不要", "hero.pagesPerMonth": "✓ 100ページ/月", "hero.trustedBy": "信頼されているチーム", "hero.altImage": "PageGenダッシュボードのCSVからページ生成ワークフロー",
  "features.badge": "機能", "features.title1": "大規模に生成するための", "features.title2": "すべてが揃っています", "features.csvUpload": "CSVアップロード", "features.csvUploadDesc": "CSVをドロップ — カラムが自動検出、検証され、数秒でマッピング準備完了。", "features.dynamicTemplates": "動的テンプレート", "features.dynamicTemplatesDesc": "{変数}プレースホルダーで再利用可能なテンプレートを作成。", "features.smartMapping": "スマートマッピング", "features.smartMappingDesc": "ドラッグ＆ドロップのフィールドマッピングとリアルタイムプレビュー。", "features.bulkGeneration": "一括生成", "features.bulkGenerationDesc": "リアルタイム進捗追跡で1つのキャンペーンで数百ページを生成。", "features.multiPlatform": "マルチプラットフォーム公開", "features.multiPlatformDesc": "WordPress & Shopifyに API経由で公開。無制限のウェブサイトを接続。", "features.campaignAnalytics": "キャンペーン分析", "features.campaignAnalyticsDesc": "進捗、成功率、ライブURL、詳細なエラーログを追跡。",
  "showcase.importTag": "インポート", "showcase.importTitle": "スマートCSV処理", "showcase.importDesc": "任意のCSVをインポート — カラム自動検出、データ検証、最適マッピング自動提案。", "showcase.importH1": "自動検出", "showcase.importH2": "バリデーション", "showcase.importH3": "エラー処理", "showcase.importH4": "バッチ対応", "showcase.buildTag": "構築", "showcase.buildTitle": "ビジュアルテンプレートエディタ", "showcase.buildDesc": "ビジュアルエディタでテンプレートを作成。動的変数をどこにでも挿入。", "showcase.buildH1": "ビジュアルエディタ", "showcase.buildH2": "ライブプレビュー", "showcase.buildH3": "変数", "showcase.buildH4": "SEOタグ", "showcase.deployTag": "デプロイ", "showcase.deployTitle": "ワンクリック公開", "showcase.deployDesc": "キャンペーンを実行し、リアルタイムでページが公開される様子を確認。", "showcase.deployH1": "リアルタイム", "showcase.deployH2": "エラーログ", "showcase.deployH3": "直接リンク", "showcase.deployH4": "一括デプロイ", "showcase.live": "ライブ", "showcase.deploying": "デプロイ中...",
  "video.badge": "デモ", "video.title": "実際の動作を見る", "video.description": "チームが数分で数千ページを生成する方法をご覧ください。", "video.watchDemo": "2分間のデモを見る", "video.pagesGenerated": "生成ページ数", "video.avgTrafficBoost": "平均トラフィック増加", "video.setupTime": "セットアップ時間", "video.uptimeSLA": "アップタイムSLA",
  "howItWorks.badge": "仕組み", "howItWorks.title": "公開ページまでの4ステップ", "howItWorks.step1Title": "サイトを接続", "howItWorks.step1Desc": "API認証情報でWordPressまたはShopifyサイトを接続。", "howItWorks.step2Title": "テンプレート作成", "howItWorks.step2Desc": "{変数}プレースホルダーでレイアウトを構築。", "howItWorks.step3Title": "アップロード＆マッピング", "howItWorks.step3Desc": "CSVデータをアップロードしてテンプレートフィールドにマッピング。", "howItWorks.step4Title": "生成＆公開", "howItWorks.step4Desc": "実行をクリック。リアルタイムでページが公開されます。",
  "reviews.badge": "レビュー", "reviews.title": "2,000以上のチームに愛用", "reviews.description": "SEOプロフェッショナルがPageGenについて語ること。",
  "pricing.badge": "料金", "pricing.title": "シンプルで透明な料金体系", "pricing.description": "無料で開始。成長に合わせてスケール。隠れた費用なし。いつでもキャンセル可能。", "pricing.monthly": "月額", "pricing.yearly": "年額", "pricing.save": "20%割引", "pricing.mostPopular": "最も人気", "pricing.comparePlans": "プラン比較", "pricing.compareDesc": "各プランの内容を確認", "pricing.feature": "機能", "pricing.starter": "Starter", "pricing.starterDesc": "個人や小規模プロジェクトに最適", "pricing.pro": "Pro", "pricing.proDesc": "成長中のビジネスやマーケターに最適", "pricing.agency": "Agency", "pricing.agencyDesc": "代理店や企業チーム向け", "pricing.getStarted": "始める", "pricing.startProTrial": "Proを試す", "pricing.contactSales": "営業に連絡", "pricing.pagesMonth": "ページ / 月", "pricing.aiGenerations": "AI生成", "pricing.templates": "テンプレート", "pricing.websites": "ウェブサイト", "pricing.wordpress": "WordPress", "pricing.shopify": "Shopify", "pricing.socialSharing": "ソーシャル共有", "pricing.storeGenerator": "AIストアジェネレーター", "pricing.googleIndexing": "Googleインデックス", "pricing.internalLinks": "内部リンク", "pricing.apiAccess": "APIアクセス", "pricing.teamCollaboration": "チームコラボレーション", "pricing.support": "サポート", "pricing.unlimited": "無制限", "pricing.email": "メール", "pricing.priority": "優先", "pricing.dedicated": "専用", "pricing.billed": "請求", "pricing.year": "年", "pricing.mo": "/月", "pricing.pagesPerMonth": "ページ/月",
  "faq.badge": "FAQ", "faq.title": "よくある質問", "faq.q1": "どのウェブサイトを接続できますか？", "faq.a1": "WordPress（REST API）とShopify（Admin API）。その他の統合も近日中に追加予定。", "faq.q2": "CSV処理はどのように機能しますか？", "faq.a2": "任意のCSVをアップロード — カラムを自動検出。各カラムをテンプレート変数にマッピング。各行がページになります。", "faq.q3": "公開前にプレビューできますか？", "faq.a3": "はい。「Dry Run」でプレビューを生成できます。", "faq.q4": "ページが失敗した場合はどうなりますか？", "faq.a4": "失敗したページは詳細なエラーとともに記録されます。ワンクリックでリトライ可能。", "faq.q5": "APIはありますか？", "faq.a5": "はい、ProとAgencyプランにはAPIアクセスが含まれます。", "faq.q6": "いつでもキャンセルできますか？", "faq.a6": "もちろん。契約なし、義務なし。",
  "cta.title": "大規模なコンテンツ展開の準備はできましたか？", "cta.description": "2,000以上のSEOチームに参加しましょう。", "cta.getStarted": "無料で始める", "cta.viewPricing": "料金を見る",
  "footer.description": "データドリブンなコンテンツを大規模に展開。CSVから公開ページまで数分で。", "footer.product": "製品", "footer.integrations": "統合", "footer.company": "会社", "footer.legal": "法的情報", "footer.features": "機能", "footer.pricing": "料金", "footer.faq": "FAQ", "footer.changelog": "更新履歴", "footer.wordpress": "WordPress", "footer.shopify": "Shopify", "footer.apiDocs": "APIドキュメント", "footer.about": "会社概要", "footer.blog": "ブログ", "footer.contact": "お問い合わせ", "footer.privacy": "プライバシー", "footer.terms": "利用規約", "footer.rights": "全著作権所有。",
  "dashboard.search": "検索...", "dashboard.settings": "設定", "dashboard.billing": "請求", "dashboard.logout": "ログアウト",
  "sidebar.main": "メイン", "sidebar.tools": "ツール", "sidebar.account": "アカウント", "sidebar.dashboard": "ダッシュボード", "sidebar.campaigns": "キャンペーン", "sidebar.generatedPages": "生成ページ", "sidebar.templates": "テンプレート", "sidebar.marketplace": "マーケットプレイス", "sidebar.websiteContent": "サイトコンテンツ", "sidebar.aiScanner": "AIスキャナー", "sidebar.discovery": "ディスカバリー", "sidebar.analytics": "分析", "sidebar.performance": "パフォーマンス", "sidebar.abTesting": "A/Bテスト", "sidebar.indexing": "インデックス", "sidebar.storeGenerator": "ストアジェネレーター", "sidebar.websites": "ウェブサイト", "sidebar.billing": "請求", "sidebar.settings": "設定", "sidebar.workspaceSettings": "ワークスペース設定", "sidebar.admin": "管理者", "sidebar.usage": "使用状況", "sidebar.pagesGenerated": "今月の生成ページ数", "sidebar.logout": "ログアウト", "sidebar.dataCsv": "データ / CSV", "sidebar.contentCalendar": "コンテンツカレンダー", "sidebar.seoAudit": "SEO監査",
  "auth.home": "ホーム", "auth.signIn": "ログイン", "auth.signUp": "登録", "auth.welcomeBack": "おかえりなさい", "auth.createAccount": "アカウント作成", "auth.signInDesc": "ダッシュボードにアクセスするにはログインしてください", "auth.signUpDesc": "数分でページ生成を開始", "auth.fullName": "氏名", "auth.fullNamePlaceholder": "山田太郎", "auth.companyName": "会社名 / 組織名", "auth.companyPlaceholder": "株式会社Acme", "auth.companyRequired": "会社名は必須です。", "auth.agencyPlanInfo": "すべての新規アカウントにはAgencyプラン（10,000ページ、5,000 AI生成）が含まれます。", "auth.generatePassword": "強力なパスワードを生成", "auth.passwordGenerated": "パスワード生成完了", "auth.passwordGeneratedDesc": "強力なパスワードが生成されました。続行する前にコピーしてください。", "auth.acceptTerms": "同意します", "auth.termsOfService": "利用規約", "auth.privacyPolicy": "プライバシーポリシー", "auth.and": "と", "auth.termsRequired": "続行するには規約に同意する必要があります。", "auth.email": "メールアドレス", "auth.emailPlaceholder": "you@example.jp", "auth.password": "パスワード", "auth.forgotPassword": "パスワードをお忘れですか？", "auth.signingIn": "ログイン中...", "auth.creatingAccount": "アカウント作成中...", "auth.orContinueWith": "または以下で続行", "auth.noAccount": "アカウントをお持ちでないですか？", "auth.hasAccount": "すでにアカウントをお持ちですか？", "auth.terms": "続行することで利用規約とプライバシーポリシーに同意します。", "auth.loginFailed": "ログイン失敗", "auth.signupFailed": "登録失敗", "auth.passwordTooWeak": "パスワードがすべての要件を満たしていません。", "auth.invalidEmail": "有効なメールアドレスを入力してください。", "auth.checkEmail": "メールを確認", "auth.confirmationSent": "確認リンクを送信しました。", "auth.enterEmail": "メールを入力", "auth.enterEmailDesc": "まずメールアドレスを入力してください。", "auth.resetSent": "リセットメール送信済み", "auth.resetSentDesc": "受信トレイを確認してください。", "auth.googleFailed": "Googleログイン失敗", "auth.appleFailed": "Appleログイン失敗", "auth.contentLanguage": "コンテンツ言語", "auth.contentLanguageDesc": "AI生成コンテンツはこの言語で作成されます", "auth.rememberMe": "ログイン状態を維持", "auth.errorInvalidCredentials": "メールまたはパスワードが正しくありません。", "auth.errorEmailNotVerified": "メールアドレスがまだ認証されていません。", "auth.errorTooManyAttempts": "試行回数が多すぎます。しばらくお待ちください。", "auth.setNewPassword": "新しいパスワードを設定", "auth.setNewPasswordDesc": "アカウントを保護する強力なパスワードを選択してください。", "auth.newPassword": "新しいパスワード", "auth.confirmPassword": "パスワード確認", "auth.updatePassword": "パスワードを更新", "auth.updating": "更新中...", "auth.passwordUpdated": "パスワード更新完了", "auth.passwordUpdatedDesc": "新しいパスワードでログインできます。", "auth.resetFailed": "パスワードリセット失敗", "auth.passwordsMismatch": "パスワードが一致しません", "auth.passwordsMatch": "パスワードが一致しています", "auth.invalidResetLink": "無効または期限切れのリンク", "auth.invalidResetLinkDesc": "このリンクは無効です。新しいリンクをリクエストしてください。", "auth.backToLogin": "ログインに戻る", "auth.pwRuleMinLength": "8文字以上", "auth.pwRuleUppercase": "大文字1つ", "auth.pwRuleLowercase": "小文字1つ", "auth.pwRuleNumber": "数字1つ", "auth.pwRuleSpecial": "特殊文字1つ", "auth.rateLimited": "お待ちください", "auth.rateLimitedDesc": "{seconds}秒後に再度リクエストできます。", "auth.passwordStrength": "パスワード強度", "auth.strengthWeak": "弱い", "auth.strengthMedium": "普通", "auth.strengthStrong": "強い",
  "sidebar.pgpSection": "Page Generator Pro", "sidebar.pgpKeywords": "キーワード", "sidebar.pgpGenerate": "生成", "sidebar.pgpTerms": "用語",
};
export default ja;
