const ko: Record<string, string> = {
  "nav.features": "기능", "nav.howItWorks": "작동 방식", "nav.pricing": "요금제", "nav.faq": "FAQ", "nav.login": "로그인", "nav.getStarted": "시작하기", "nav.lightMode": "라이트 모드", "nav.darkMode": "다크 모드",
  "hero.badge": "AI 기반 콘텐츠 생성 지원", "hero.title1": "데이터를", "hero.title2": "게시된 페이지로 변환", "hero.description": "프로그래밍 방식의 SEO, SEA, GEO 페이지를 위한 멀티테넌트 플랫폼. CSV를 업로드하고, 템플릿에 매핑하고, 수백 개의 최적화된 페이지를 몇 분 만에 생성 및 배포하세요.", "hero.cta": "무료로 시작", "hero.watchDemo": "데모 보기", "hero.freeStart": "✓ 무료 시작", "hero.noCreditCard": "✓ 신용카드 불필요", "hero.pagesPerMonth": "✓ 월 100페이지", "hero.trustedBy": "신뢰받는 팀", "hero.altImage": "PageGen 대시보드의 CSV에서 페이지 생성 워크플로",
  "features.badge": "기능", "features.title1": "대규모 생성에 필요한", "features.title2": "모든 것", "features.csvUpload": "CSV 업로드", "features.csvUploadDesc": "CSV를 드롭하면 열이 자동 감지, 검증되어 몇 초 만에 매핑 준비 완료.", "features.dynamicTemplates": "동적 템플릿", "features.dynamicTemplatesDesc": "{변수} 플레이스홀더가 있는 재사용 가능한 템플릿을 생성.", "features.smartMapping": "스마트 매핑", "features.smartMappingDesc": "드래그 앤 드롭 필드 매핑과 실시간 미리보기.", "features.bulkGeneration": "대량 생성", "features.bulkGenerationDesc": "실시간 진행 추적으로 하나의 캠페인에서 수백 페이지 생성.", "features.multiPlatform": "멀티 플랫폼 게시", "features.multiPlatformDesc": "API를 통해 WordPress & Shopify에 게시. 무제한 웹사이트 연결.", "features.campaignAnalytics": "캠페인 분석", "features.campaignAnalyticsDesc": "진행 상황, 성공률, 라이브 URL, 상세 오류 로그 추적.",
  "showcase.importTag": "가져오기", "showcase.importTitle": "스마트 CSV 처리", "showcase.importDesc": "모든 CSV를 가져오기 — 열 자동 감지, 데이터 검증, 최적 매핑 자동 제안.", "showcase.importH1": "자동 감지", "showcase.importH2": "검증", "showcase.importH3": "오류 처리", "showcase.importH4": "배치 준비", "showcase.buildTag": "구축", "showcase.buildTitle": "비주얼 템플릿 편집기", "showcase.buildDesc": "비주얼 편집기로 템플릿을 생성. 동적 변수를 어디에나 삽입.", "showcase.buildH1": "비주얼 편집기", "showcase.buildH2": "실시간 미리보기", "showcase.buildH3": "변수", "showcase.buildH4": "SEO 태그", "showcase.deployTag": "배포", "showcase.deployTitle": "원클릭 게시", "showcase.deployDesc": "캠페인을 실행하고 실시간으로 페이지가 게시되는 것을 확인.", "showcase.deployH1": "실시간", "showcase.deployH2": "오류 로그", "showcase.deployH3": "직접 링크", "showcase.deployH4": "대량 배포", "showcase.live": "라이브", "showcase.deploying": "배포 중...",
  "video.badge": "데모", "video.title": "실제 동작 보기", "video.description": "팀이 몇 분 만에 수천 페이지를 생성하는 방법을 확인하세요.", "video.watchDemo": "2분 데모 보기", "video.pagesGenerated": "생성된 페이지", "video.avgTrafficBoost": "평균 트래픽 증가", "video.setupTime": "설정 시간", "video.uptimeSLA": "업타임 SLA",
  "howItWorks.badge": "작동 방식", "howItWorks.title": "게시된 페이지까지 4단계", "howItWorks.step1Title": "사이트 연결", "howItWorks.step1Desc": "API 인증으로 WordPress 또는 Shopify 사이트 연결.", "howItWorks.step2Title": "템플릿 생성", "howItWorks.step2Desc": "{변수} 플레이스홀더로 레이아웃 구축.", "howItWorks.step3Title": "업로드 & 매핑", "howItWorks.step3Desc": "CSV 데이터를 업로드하고 열을 템플릿 필드에 매핑.", "howItWorks.step4Title": "생성 & 게시", "howItWorks.step4Desc": "실행 클릭. 실시간으로 페이지가 게시됩니다.",
  "reviews.badge": "리뷰", "reviews.title": "2,000개 이상의 팀이 사용", "reviews.description": "SEO 전문가들이 PageGen에 대해 말하는 것.",
  "pricing.badge": "요금제", "pricing.title": "간단하고 투명한 요금제", "pricing.description": "무료로 시작. 성장에 맞춰 확장. 숨겨진 비용 없음. 언제든 취소 가능.", "pricing.monthly": "월간", "pricing.yearly": "연간", "pricing.save": "20% 절약", "pricing.mostPopular": "가장 인기", "pricing.comparePlans": "플랜 비교", "pricing.compareDesc": "각 플랜의 내용을 확인", "pricing.feature": "기능", "pricing.starter": "Starter", "pricing.starterDesc": "개인 및 소규모 프로젝트에 적합", "pricing.pro": "Pro", "pricing.proDesc": "성장하는 비즈니스와 마케터에 최적", "pricing.agency": "Agency", "pricing.agencyDesc": "에이전시 및 기업 팀용", "pricing.getStarted": "시작하기", "pricing.startProTrial": "Pro 체험", "pricing.contactSales": "영업팀 연락", "pricing.pagesMonth": "페이지 / 월", "pricing.aiGenerations": "AI 생성", "pricing.templates": "템플릿", "pricing.websites": "웹사이트", "pricing.wordpress": "WordPress", "pricing.shopify": "Shopify", "pricing.socialSharing": "소셜 공유", "pricing.storeGenerator": "AI 스토어 생성기", "pricing.googleIndexing": "Google 색인", "pricing.internalLinks": "내부 링크", "pricing.apiAccess": "API 접근", "pricing.teamCollaboration": "팀 협업", "pricing.support": "지원", "pricing.unlimited": "무제한", "pricing.email": "이메일", "pricing.priority": "우선", "pricing.dedicated": "전담", "pricing.billed": "청구", "pricing.year": "년", "pricing.mo": "/월", "pricing.pagesPerMonth": "페이지/월",
  "faq.badge": "FAQ", "faq.title": "자주 묻는 질문", "faq.q1": "어떤 웹사이트를 연결할 수 있나요?", "faq.a1": "WordPress(REST API)와 Shopify(Admin API). 더 많은 통합이 곧 추가됩니다.", "faq.q2": "CSV 처리는 어떻게 작동하나요?", "faq.a2": "모든 CSV를 업로드 — 시스템이 열을 자동 감지. 각 열을 템플릿 변수에 매핑. 각 행이 페이지가 됩니다.", "faq.q3": "게시 전 미리볼 수 있나요?", "faq.a3": "네. 'Dry Run'으로 미리보기를 생성할 수 있습니다.", "faq.q4": "페이지가 실패하면 어떻게 되나요?", "faq.a4": "실패한 페이지는 상세 오류와 함께 기록됩니다. 원클릭으로 재시도 가능.", "faq.q5": "API가 있나요?", "faq.a5": "네, Pro와 Agency 플랜에 API 접근이 포함됩니다.", "faq.q6": "언제든 취소할 수 있나요?", "faq.a6": "물론입니다. 계약 없음, 의무 없음.",
  "cta.title": "대규모 콘텐츠 배포 준비가 되셨나요?", "cta.description": "이미 수천 페이지를 생성하는 2,000개 이상의 SEO 팀에 합류하세요.", "cta.getStarted": "무료로 시작", "cta.viewPricing": "요금제 보기",
  "footer.description": "데이터 기반 콘텐츠를 대규모로 배포. CSV에서 게시된 페이지까지 몇 분 만에.", "footer.product": "제품", "footer.integrations": "통합", "footer.company": "회사", "footer.legal": "법적 정보", "footer.features": "기능", "footer.pricing": "요금제", "footer.faq": "FAQ", "footer.changelog": "변경 로그", "footer.wordpress": "WordPress", "footer.shopify": "Shopify", "footer.apiDocs": "API 문서", "footer.about": "소개", "footer.blog": "블로그", "footer.contact": "문의", "footer.privacy": "개인정보", "footer.terms": "이용약관", "footer.rights": "모든 권리 보유.",
  "dashboard.search": "검색...", "dashboard.settings": "설정", "dashboard.billing": "청구", "dashboard.logout": "로그아웃",
  "sidebar.main": "메인", "sidebar.tools": "도구", "sidebar.account": "계정", "sidebar.dashboard": "대시보드", "sidebar.campaigns": "캠페인", "sidebar.generatedPages": "생성된 페이지", "sidebar.templates": "템플릿", "sidebar.marketplace": "마켓플레이스", "sidebar.websiteContent": "사이트 콘텐츠", "sidebar.aiScanner": "AI 스캐너", "sidebar.discovery": "디스커버리", "sidebar.analytics": "분석", "sidebar.performance": "성능", "sidebar.abTesting": "A/B 테스트", "sidebar.indexing": "색인", "sidebar.storeGenerator": "스토어 생성기", "sidebar.websites": "웹사이트", "sidebar.billing": "청구", "sidebar.settings": "설정", "sidebar.workspaceSettings": "워크스페이스 설정", "sidebar.admin": "관리자", "sidebar.usage": "사용량", "sidebar.pagesGenerated": "이번 달 생성된 페이지", "sidebar.logout": "로그아웃", "sidebar.dataCsv": "데이터 / CSV", "sidebar.contentCalendar": "콘텐츠 캘린더", "sidebar.seoAudit": "SEO 감사",
  "auth.home": "홈", "auth.signIn": "로그인", "auth.signUp": "가입", "auth.welcomeBack": "다시 오신 것을 환영합니다", "auth.createAccount": "계정 만들기", "auth.signInDesc": "대시보드에 접근하려면 로그인하세요", "auth.signUpDesc": "몇 분 만에 페이지 생성을 시작하세요", "auth.fullName": "이름", "auth.fullNamePlaceholder": "홍길동", "auth.companyName": "회사 / 조직", "auth.companyPlaceholder": "주식회사 Acme", "auth.companyRequired": "회사명은 필수입니다.", "auth.agencyPlanInfo": "모든 새 계정에는 10,000페이지와 5,000 AI 생성이 포함된 Agency 플랜이 포함됩니다.", "auth.generatePassword": "강력한 비밀번호 생성", "auth.passwordGenerated": "비밀번호 생성됨", "auth.passwordGeneratedDesc": "강력한 비밀번호가 생성되었습니다. 계속하기 전에 복사하세요.", "auth.acceptTerms": "동의합니다", "auth.termsOfService": "서비스 약관", "auth.privacyPolicy": "개인정보 처리방침", "auth.and": "및", "auth.termsRequired": "계속하려면 약관에 동의해야 합니다.", "auth.email": "이메일 주소", "auth.emailPlaceholder": "you@example.kr", "auth.password": "비밀번호", "auth.forgotPassword": "비밀번호를 잊으셨나요?", "auth.signingIn": "로그인 중...", "auth.creatingAccount": "계정 생성 중...", "auth.orContinueWith": "또는 다음으로 계속", "auth.noAccount": "계정이 없으신가요?", "auth.hasAccount": "이미 계정이 있으신가요?", "auth.terms": "계속하면 서비스 약관 및 개인정보 처리방침에 동의합니다.", "auth.loginFailed": "로그인 실패", "auth.signupFailed": "가입 실패", "auth.passwordTooWeak": "비밀번호가 모든 요구 사항을 충족하지 않습니다.", "auth.invalidEmail": "유효한 이메일 주소를 입력하세요.", "auth.checkEmail": "이메일 확인", "auth.confirmationSent": "확인 링크를 보냈습니다.", "auth.enterEmail": "이메일 입력", "auth.enterEmailDesc": "먼저 이메일 주소를 입력하세요.", "auth.resetSent": "재설정 이메일 전송됨", "auth.resetSentDesc": "받은편지함을 확인하세요.", "auth.googleFailed": "Google 로그인 실패", "auth.appleFailed": "Apple 로그인 실패", "auth.contentLanguage": "콘텐츠 언어", "auth.contentLanguageDesc": "AI 생성 콘텐츠가 이 언어로 작성됩니다", "auth.rememberMe": "로그인 유지", "auth.errorInvalidCredentials": "이메일 또는 비밀번호가 올바르지 않습니다.", "auth.errorEmailNotVerified": "이메일이 아직 인증되지 않았습니다.", "auth.errorTooManyAttempts": "너무 많은 시도. 잠시 기다려주세요.", "auth.setNewPassword": "새 비밀번호 설정", "auth.setNewPasswordDesc": "계정을 보호할 강력한 비밀번호를 선택하세요.", "auth.newPassword": "새 비밀번호", "auth.confirmPassword": "비밀번호 확인", "auth.updatePassword": "비밀번호 업데이트", "auth.updating": "업데이트 중...", "auth.passwordUpdated": "비밀번호 업데이트됨", "auth.passwordUpdatedDesc": "새 비밀번호로 로그인할 수 있습니다.", "auth.resetFailed": "비밀번호 재설정 실패", "auth.passwordsMismatch": "비밀번호가 일치하지 않습니다", "auth.passwordsMatch": "비밀번호가 일치합니다", "auth.invalidResetLink": "유효하지 않거나 만료된 링크", "auth.invalidResetLinkDesc": "이 링크는 더 이상 유효하지 않습니다.", "auth.backToLogin": "로그인으로 돌아가기", "auth.pwRuleMinLength": "최소 8자", "auth.pwRuleUppercase": "대문자 1개", "auth.pwRuleLowercase": "소문자 1개", "auth.pwRuleNumber": "숫자 1개", "auth.pwRuleSpecial": "특수문자 1개", "auth.rateLimited": "잠시 기다려주세요", "auth.rateLimitedDesc": "{seconds}초 후에 다시 요청할 수 있습니다.", "auth.passwordStrength": "비밀번호 강도", "auth.strengthWeak": "약함", "auth.strengthMedium": "보통", "auth.strengthStrong": "강함",
};
  "sidebar.pgpSection": "Page Generator Pro", "sidebar.pgpKeywords": "키워드", "sidebar.pgpGenerate": "생성", "sidebar.pgpTerms": "용어",
export default ko;
