// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://qbrqxmtzfbusyspdtojz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicnF4bXR6ZmJ1c3lzcGR0b2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4NjEyMDIsImV4cCI6MjEwMzQzNzIwMn0.7-KIhSf1-XEWSNrKYtKUqiUTsIuVRAAbuOHfOzirUxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});